"use client";

import Link from "next/link";
import { useState } from "react";
import { applyAutomationTemplateAction, createAutomationAction, duplicateAutomationAction, setAutomationStatusAction, testAutomationAction } from "@/app/admin/automation-actions";
import type { AutomationBoard as Board, AutomationFilters, AutomationListItem, AutomationRun } from "@/lib/automations/types";
import { AUTOMATION_CATEGORIES, AUTOMATION_STATUSES, titleCase } from "@/lib/automations/types";
import { IconAlert, IconArrowRight, IconCheck, IconClock, IconGrid, IconLayers, IconPlus, IconPulse, IconRepeat, IconSearch, IconX, IconZap } from "../Icons";
import styles from "./Automations.module.css";

const ROOT = "/admin/automations";
const when = (value: string | null) => !value ? "Never" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const pct = (value: number | null) => value === null ? "—" : `${value}%`;

function Modal({ title, subtitle, close, children }: { title: string; subtitle: string; close: () => void; children: React.ReactNode }) {
  return <div className={styles.scrim} onMouseDown={(event) => event.target === event.currentTarget && close()}><section className={styles.modal} role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2><p>{subtitle}</p></div><button type="button" onClick={close} aria-label="Close"><IconX size={18}/></button></header>{children}</section></div>;
}

function NewAutomation({ board, close }: { board: Board; close: () => void }) {
  return <form action={createAutomationAction} className={styles.form}>
    <div className={styles.stepper}>{["Basic Info","Trigger","Conditions","Actions","Test","Activate"].map((step, index) => <span className={index === 0 ? styles.current : ""} key={step}><b>{index + 1}</b>{step}</span>)}</div>
    <label>Automation Name<input name="name" required autoFocus placeholder="e.g. New lead task"/></label><label>Description<textarea name="description" rows={3} placeholder="What this rule does and why"/></label>
    <div className={styles.two}><label>Category<select name="category" defaultValue="sales">{AUTOMATION_CATEGORIES.map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label>Owner<select name="owner_id"><option value="">Me</option>{board.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label></div>
    <label>Trigger<select name="trigger_definition_id" required defaultValue=""><option value="" disabled>Select a real application event</option>{AUTOMATION_CATEGORIES.map((category) => <optgroup label={titleCase(category)} key={category}>{board.triggers.filter((trigger) => trigger.area === category).map((trigger) => <option key={trigger.id} value={trigger.id}>{trigger.name}</option>)}</optgroup>)}</select></label>
    <div className={styles.two}><label>Tags<input name="tags" placeholder="sales, follow-up"/></label><label>Manual minutes saved / run<input name="estimated_minutes_saved" type="number" min="0" placeholder="Optional"/></label></div>
    <p className={styles.safeNote}>New automations begin as drafts. Add actions and complete a dry run before activation.</p>
    <div className={styles.formActions}><button type="button" className={styles.secondary} onClick={close}>Cancel</button><button className={styles.primary}>Create Draft <IconArrowRight size={14}/></button></div>
  </form>;
}

function Kpis({ board }: { board: Board }) {
  const cards = [["Active Automations", board.kpis.active, "Rules currently listening"], ["Runs This Month", board.kpis.runsThisMonth, "Recorded executions"], ["Successful Runs", board.kpis.successfulRuns, "Completed successfully"], ["Failed Runs", board.kpis.failedRuns, "Requires investigation"], ["Success Rate", pct(board.kpis.successRate), "Completed runs only"], ["Needs Attention", board.kpis.needsAttention, "Warnings and critical"]];
  return <div className={styles.kpis}>{cards.map(([label, value, note], index) => <article key={label}><span className={index === 3 || index === 5 ? styles.dangerIcon : ""}>{index === 0 ? <IconRepeat/> : index === 1 ? <IconPulse/> : index === 2 ? <IconCheck/> : index === 3 || index === 5 ? <IconAlert/> : <IconZap/>}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</div>;
}

function Attention({ board }: { board: Board }) {
  const items = board.automations.filter((item) => item.health === "critical" || item.health === "warning").slice(0, 4);
  if (!items.length) return <section className={styles.attention}><div className={styles.attentionTitle}><IconCheck size={18}/><b>No automation needs attention</b><span>There are no recorded configuration or run failures.</span></div></section>;
  return <section className={styles.attention}><div className={styles.attentionTitle}><IconAlert size={18}/><b>Needs Attention</b><span>{board.kpis.needsAttention} automation{board.kpis.needsAttention === 1 ? "" : "s"}</span></div><div className={styles.attentionItems}>{items.map((item) => <Link href={`${ROOT}/${item.id}?tab=errors`} key={item.id}><i className={styles[item.health]}/><span><b>{item.name}</b><small>{item.failures ? `${item.failures} failed run${item.failures === 1 ? "" : "s"} this month` : item.trigger === "Not configured" ? "Trigger is not configured" : "Configuration requires review"}</small></span></Link>)}</div><Link href={`${ROOT}?health=warning`}>View All <IconArrowRight size={13}/></Link></section>;
}

function Toolbar({ board, filters }: { board: Board; filters: AutomationFilters }) {
  return <form className={styles.toolbar}><input type="hidden" name="category" value={filters.category}/><div className={styles.search}><IconSearch size={15}/><input name="q" defaultValue={filters.q} placeholder="Search automations…"/></div><select name="status" defaultValue={filters.status}><option value="">Status</option>{AUTOMATION_STATUSES.map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select><select name="trigger" defaultValue={filters.trigger}><option value="">Trigger</option>{board.triggers.map((trigger) => <option key={trigger.id} value={trigger.key}>{trigger.name}</option>)}</select><select name="owner" defaultValue={filters.owner}><option value="">Owner</option>{board.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><select name="health" defaultValue={filters.health}><option value="">Health</option>{["healthy","warning","critical","unknown"].map((value) => <option key={value}>{titleCase(value)}</option>)}</select><select name="lastRun" defaultValue={filters.lastRun}><option value="">Last Run</option><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><select name="sort" defaultValue={filters.sort}><option value="last_run">Last Run</option><option value="runs">Most Runs</option><option value="success">Lowest Success Rate</option><option value="updated">Recently Updated</option><option value="name">Name</option></select><button>Apply</button><div className={styles.toggle}><Link className={filters.view === "table" ? styles.on : ""} href={{ pathname: ROOT, query: { ...filters, view: "table" } }}>☷ Table</Link><Link className={filters.view === "cards" ? styles.on : ""} href={{ pathname: ROOT, query: { ...filters, view: "cards" } }}><IconGrid size={13}/> Cards</Link></div></form>;
}

function RowActions({ item, canManage }: { item: AutomationListItem; canManage: boolean }) {
  if (!canManage) return <Link className={styles.inlineLink} href={`${ROOT}/${item.id}`}>View</Link>;
  return <details className={styles.menu}><summary>•••</summary><div><Link href={`${ROOT}/${item.id}`}>View / Edit</Link><form action={testAutomationAction}><input type="hidden" name="automation_id" value={item.id}/><button name="mode" value="dry_run">Dry Run</button></form><form action={setAutomationStatusAction}><input type="hidden" name="automation_id" value={item.id}/><button name="status" value={item.status === "active" ? "paused" : "active"}>{item.status === "active" ? "Pause" : "Activate"}</button></form><form action={duplicateAutomationAction}><input type="hidden" name="automation_id" value={item.id}/><button>Duplicate</button></form><Link href={`${ROOT}/${item.id}?tab=runs`}>Run History</Link>{!item.lockedExecution ? <form action={setAutomationStatusAction}><input type="hidden" name="automation_id" value={item.id}/><button name="status" value="archived">Archive</button></form> : null}</div></details>;
}

function AutomationsTable({ board, canManage }: { board: Board; canManage: boolean }) {
  if (!board.automations.length) return <Empty canManage={canManage}/>;
  return <div className={styles.tableWrap}><table><thead><tr><th>Automation</th><th>Area</th><th>Trigger</th><th>Status</th><th>Runs</th><th>Success Rate</th><th>Last Run</th><th>Owner</th><th>Actions</th></tr></thead><tbody>{board.automations.map((item) => <tr key={item.id}><td><Link className={styles.nameCell} href={`${ROOT}/${item.id}`}><span className={styles.automationIcon}><IconRepeat size={16}/></span><span><b>{item.name}</b><small>{item.description ?? "No description"}</small></span></Link></td><td><span className={styles.area}>{titleCase(item.category)}</span></td><td>{item.trigger}</td><td><span className={`${styles.badge} ${styles[item.status]}`}>{titleCase(item.status)}</span><small className={`${styles.healthText} ${styles[item.health]}`}>{titleCase(item.health)}</small></td><td>{item.runs}</td><td>{pct(item.successRate)}</td><td>{when(item.lastRunAt)}</td><td>{item.owner ?? "Unassigned"}</td><td><RowActions item={item} canManage={canManage}/></td></tr>)}</tbody></table></div>;
}

function Cards({ board, canManage }: { board: Board; canManage: boolean }) { return board.automations.length ? <div className={styles.cards}>{board.automations.map((item) => <article key={item.id}><header><span className={styles.automationIcon}><IconRepeat/></span><div><h3>{item.name}</h3><p>{item.description ?? "No description"}</p></div><RowActions item={item} canManage={canManage}/></header><div className={styles.cardMeta}><span><small>Trigger</small><b>{item.trigger}</b></span><span><small>Status</small><b>{titleCase(item.status)}</b></span><span><small>Runs</small><b>{item.runs}</b></span><span><small>Success</small><b>{pct(item.successRate)}</b></span></div><footer><span className={`${styles.healthText} ${styles[item.health]}`}>{titleCase(item.health)}</span><Link href={`${ROOT}/${item.id}`}>View Details <IconArrowRight size={13}/></Link></footer></article>)}</div> : <Empty canManage={canManage}/>; }

function Runs({ runs }: { runs: AutomationRun[] }) { return runs.length ? <div className={styles.tableWrap}><table><thead><tr><th>Run ID</th><th>Automation</th><th>Triggered At</th><th>Trigger</th><th>Status</th><th>Mode</th><th>Duration</th><th>Error</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><code>{run.id.slice(0, 8)}</code></td><td><Link className={styles.inlineLink} href={`${ROOT}/${run.automationId}?tab=runs&run=${run.id}`}>{run.automationName}</Link></td><td>{when(run.startedAt)}</td><td>{run.triggerSummary ?? titleCase(run.triggerKey)}</td><td><span className={`${styles.badge} ${styles[run.status]}`}>{titleCase(run.status)}</span></td><td>{titleCase(run.mode)}</td><td>{run.durationMs === null ? "—" : `${run.durationMs} ms`}</td><td>{run.errorSummary ?? "—"}</td></tr>)}</tbody></table></div> : <div className={styles.empty}><IconClock size={28}/><h2>No runs yet</h2><p>No automation execution has been recorded.</p></div>; }

function Templates({ board, canManage }: { board: Board; canManage: boolean }) { return <div className={styles.cards}>{board.templates.map((template) => <article key={template.id}><header><span className={styles.automationIcon}><IconLayers/></span><div><h3>{template.name}</h3><p>{template.description}</p></div></header><div className={styles.templateTag}>{titleCase(template.category)}</div>{canManage ? <form action={applyAutomationTemplateAction}><input type="hidden" name="template_id" value={template.id}/><button className={styles.primary}>Use Template <IconArrowRight size={13}/></button></form> : null}</article>)}</div>; }

function Empty({ canManage }: { canManage: boolean }) { return <div className={styles.empty}><IconRepeat size={28}/><h2>No automations yet</h2><p>Create your first rule to start eliminating repetitive work across your business.</p>{canManage ? <span>Use New Automation above to create a safe draft.</span> : null}</div>; }

function SideRail({ board }: { board: Board }) {
  const healthy = board.automations.filter((a) => a.health === "healthy").length; const warnings = board.automations.filter((a) => a.health === "warning").length; const failed = board.automations.filter((a) => a.health === "critical").length; const known = healthy + warnings + failed; const angle = known ? healthy / known * 360 : 0; const most = [...board.automations].sort((a, b) => b.runs - a.runs)[0];
  return <aside className={styles.rail}><section><header><b>Automation Health</b><Link href={`${ROOT}?health=warning`}>View Details →</Link></header><div className={styles.health}><div className={styles.donut} style={{ "--healthy": `${angle}deg` } as React.CSSProperties}><span><b>{board.automations.length}</b>Rules</span></div><ul><li><i className={styles.green}/><span>Healthy</span><b>{healthy}</b></li><li><i className={styles.yellow}/><span>Warnings</span><b>{warnings}</b></li><li><i className={styles.red}/><span>Critical</span><b>{failed}</b></li><li><i className={styles.blue}/><span>Unknown</span><b>{board.automations.length - known}</b></li></ul></div></section><section><header><b>Recent Runs</b><Link href={`${ROOT}?view=runs`}>View All →</Link></header><div className={styles.recentRuns}>{board.runs.slice(0, 5).map((run) => <Link key={run.id} href={`${ROOT}/${run.automationId}?tab=runs&run=${run.id}`}><span className={`${styles.runDot} ${styles[run.status]}`}/><div><b>{run.automationName}</b><small>{when(run.startedAt)}</small></div><em>{titleCase(run.status)}</em></Link>)}{!board.runs.length ? <p>No runs recorded yet.</p> : null}</div></section><section><header><b>Most Active Automation</b>{most ? <Link href={`${ROOT}/${most.id}`}>View Details →</Link> : null}</header>{most ? <div className={styles.most}><span className={styles.automationIcon}><IconRepeat/></span><div><b>{most.name}</b><small>{most.runs} runs this month · {pct(most.successRate)}</small><small>Last run {when(most.lastRunAt)}</small></div></div> : <p>No automation run data yet.</p>}</section>{board.kpis.timeSavedMinutes !== null ? <section><header><b>Estimated Time Saved</b></header><strong className={styles.bigStat}>{board.kpis.timeSavedMinutes} min</strong><p>Based only on configured minutes and successful runs.</p></section> : null}</aside>;
}

export default function AutomationBoard({ board, filters, canManage }: { board: Board; filters: AutomationFilters; canManage: boolean }) {
  const [modal, setModal] = useState<"new" | null>(null); const categories = ["all", ...AUTOMATION_CATEGORIES];
  return <div className={styles.page}><header className={styles.pageHead}><div><h1>Automations</h1><p>Create, monitor, and manage rule-based actions across your entire business.</p></div><div>{canManage ? <button className={styles.primary} onClick={() => setModal("new")}><IconPlus size={15}/> New Automation</button> : null}<Link className={styles.secondary} href={`${ROOT}?view=templates`}><IconLayers size={15}/> Templates</Link><Link className={styles.secondary} href={`${ROOT}?view=runs`}><IconClock size={15}/> View Run History</Link></div></header><Kpis board={board}/><Attention board={board}/><nav className={styles.tabs}>{categories.map((category) => <Link className={(filters.category ?? "all") === category && !["runs","templates"].includes(filters.view) ? styles.activeTab : ""} href={{ pathname: ROOT, query: { category, view: "table" } }} key={category}>{category === "all" ? "All Automations" : titleCase(category)}</Link>)}</nav><div className={styles.layout}><main>{!["runs","templates"].includes(filters.view) ? <Toolbar board={board} filters={filters}/> : <div className={styles.viewTitle}><div><h2>{filters.view === "runs" ? "Run History" : "Automation Templates"}</h2><p>{filters.view === "runs" ? "Recorded executions from live, test, and dry-run modes." : "Copy a proven starting point into an editable draft."}</p></div><Link href={ROOT}>Back to Automations</Link></div>}{filters.view === "runs" ? <Runs runs={board.runs}/> : filters.view === "templates" ? <Templates board={board} canManage={canManage}/> : filters.view === "cards" ? <Cards board={board} canManage={canManage}/> : <AutomationsTable board={board} canManage={canManage}/>}</main><SideRail board={board}/></div>{modal === "new" ? <Modal title="New Automation" subtitle="Build a deterministic trigger → condition → delay → action rule." close={() => setModal(null)}><NewAutomation board={board} close={() => setModal(null)}/></Modal> : null}</div>;
}

