"use client";

import Link from "next/link";
import { useState } from "react";
import { addAutomationStepAction, deleteAutomationStepAction, duplicateAutomationAction, duplicateAutomationStepAction, moveAutomationStepAction, resolveAutomationErrorAction, setAutomationStatusAction, testAutomationAction, updateAutomationAction, updateAutomationStepAction, updateAutomationTriggerAction } from "@/app/admin/automation-actions";
import type { AutomationBoard, AutomationDetail, AutomationRun, AutomationStep } from "@/lib/automations/types";
import { AUTOMATION_CATEGORIES, titleCase } from "@/lib/automations/types";
import { IconAlert, IconArrowDown, IconArrowRight, IconArrowUp, IconPlus, IconRepeat, IconX, IconZap } from "../Icons";
import boardStyles from "./Automations.module.css";
import styles from "./AutomationDetail.module.css";

const ROOT = "/admin/automations"; const tabs = ["overview","trigger","conditions","actions","runs","errors","activity","settings"];
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "Never";
const pretty = (value: Record<string, unknown>) => JSON.stringify(value, null, 2);
const summary = (step: AutomationStep) => step.type === "trigger" ? String(step.config.event ?? step.name) : step.type === "delay" ? `${step.config.amount ?? "—"} ${step.config.unit ?? ""}` : step.type === "condition" || step.type === "branch" ? `${Array.isArray(step.config.rules) ? step.config.rules.length : 0} rule(s) · ${step.config.logic ?? "AND"}` : step.actionType ? titleCase(step.actionType) : "Configure action";

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className={boardStyles.scrim} onMouseDown={(event) => event.target === event.currentTarget && close()}><section className={boardStyles.modal} role="dialog" aria-modal="true"><header><div><h2>{title}</h2><p>Every step is stored as structured configuration.</p></div><button onClick={close} aria-label="Close"><IconX/></button></header>{children}</section></div>; }

function Header({ detail, canManage }: { detail: AutomationDetail; canManage: boolean }) { return <><Link className={styles.back} href={ROOT}>← Automations</Link><header className={styles.header}><div><div className={styles.titleLine}><h1>{detail.name}</h1><span className={`${boardStyles.badge} ${boardStyles[detail.status]}`}>{titleCase(detail.status)}</span><span className={boardStyles.area}>{titleCase(detail.category)}</span><span className={`${styles.healthBadge} ${styles[detail.health]}`}>{titleCase(detail.health)}</span></div><p>{detail.description ?? "No description configured."}</p></div>{canManage ? <div className={styles.headerActions}><form action={testAutomationAction}><input type="hidden" name="automation_id" value={detail.id}/><button className={boardStyles.secondary} name="mode" value="dry_run"><IconZap size={14}/> Dry Run</button></form><form action={setAutomationStatusAction}><input type="hidden" name="automation_id" value={detail.id}/><button className={boardStyles.primary} name="status" value={detail.status === "active" ? "paused" : "active"}>{detail.status === "active" ? "Pause" : "Activate"}</button></form><form action={duplicateAutomationAction}><input type="hidden" name="automation_id" value={detail.id}/><button className={boardStyles.secondary}>Duplicate</button></form></div> : null}</header></>; }

function Kpis({ detail }: { detail: AutomationDetail }) { const durations = detail.runsDetail.map((run) => run.durationMs).filter((value): value is number => value !== null); const average = durations.length ? Math.round(durations.reduce((sum, value) => sum + value, 0) / durations.length) : null; return <div className={styles.kpis}>{[["Runs This Month",detail.runs],["Success Rate",detail.successRate === null ? "—" : `${detail.successRate}%`],["Failed Runs",detail.failures],["Average Duration",average === null ? "—" : `${average} ms`],["Last Run",date(detail.lastRunAt)],["Next Scheduled Run",date(detail.nextRunAt)]].map(([label,value]) => <article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div>; }

function Flow({ detail, canManage }: { detail: AutomationDetail; canManage: boolean }) { const [adding, setAdding] = useState(false); return <section className={styles.flowSection}><div className={styles.sectionHead}><div><h2>Automation Flow</h2><p>Trigger → conditions → delays → actions. Branch keys keep IF / ELSE paths explicit.</p></div>{canManage && !detail.lockedExecution ? <button className={boardStyles.primary} onClick={() => setAdding(true)}><IconPlus size={14}/> Add Step</button> : null}</div><div className={styles.flow}>{detail.steps.map((step, index) => <div className={styles.flowPiece} key={step.id}><article className={`${styles.node} ${styles[step.type]}`}><header><span>{step.type === "trigger" ? "WHEN" : step.type === "condition" || step.type === "branch" ? "IF" : step.type === "delay" ? "WAIT" : "THEN"}</span><em>#{index + 1}</em></header><h3>{step.name}</h3><p>{summary(step)}</p><footer><span>{step.enabled ? "Configured" : "Disabled"}</span><small>{step.branchKey}</small></footer></article>{index < detail.steps.length - 1 ? <IconArrowRight className={styles.connector} size={18}/> : null}</div>)}</div>{!detail.steps.length ? <div className={styles.emptyFlow}>No steps configured.</div> : null}{adding ? <Modal title="Add Flow Step" close={() => setAdding(false)}><AddStep detail={detail}/></Modal> : null}</section>; }

function AddStep({ detail }: { detail: AutomationDetail }) { const [type, setType] = useState("condition"); return <form action={addAutomationStepAction} className={boardStyles.stepForm}><input type="hidden" name="automation_id" value={detail.id}/><label>Step Type<select name="step_type" value={type} onChange={(event) => setType(event.target.value)}><option value="condition">Condition</option><option value="delay">Delay</option><option value="branch">IF / ELSE Branch</option><option value="action">Action</option></select></label><label>Step Name<input name="name" placeholder="Clear operational label"/></label>{type === "condition" || type === "branch" ? <><div className={boardStyles.two}><label>Logic<select name="logic"><option>AND</option><option>OR</option></select></label><label>Field<input name="field" placeholder="lead.status"/></label></div><div className={boardStyles.two}><label>Operator<select name="operator"><option value="equals">Equals</option><option value="not_equals">Does Not Equal</option><option value="contains">Contains</option><option value="not_contains">Does Not Contain</option><option value="greater_than">Greater Than</option><option value="less_than">Less Than</option><option value="is_empty">Is Empty</option><option value="is_not_empty">Is Not Empty</option><option value="before">Before</option><option value="after">After</option><option value="in_list">In List</option><option value="not_in_list">Not In List</option></select></label><label>Value<input name="value"/></label></div></> : null}{type === "delay" ? <div className={boardStyles.two}><label>Wait<input name="amount" type="number" min="1" defaultValue="1"/></label><label>Unit<select name="unit"><option>minutes</option><option>hours</option><option>days</option><option>weeks</option></select></label><label>Timezone<input name="timezone" defaultValue="America/Chicago"/></label></div> : null}{type === "action" ? <><label>Action<select name="action_type"><option value="create_task">Create Task</option><option value="send_in_app_notification">Send In-App Notification</option></select></label><label>Task title / notification message<input name="title" placeholder="Follow up with {{lead.name}}"/><input type="hidden" name="message" value="Automation needs attention"/></label><div className={boardStyles.two}><label>Priority<select name="priority"><option>low</option><option defaultValue="medium">medium</option><option>high</option><option>urgent</option></select></label><label>Due in days<input name="due_in_days" type="number" min="0" defaultValue="1"/></label></div></> : null}<p className={boardStyles.safeNote}>Supported variables include lead.name, lead.email, client.name, project.name, invoice.amount, and task.title.</p><div className={boardStyles.formActions}><button className={boardStyles.primary}>Add Step</button></div></form>; }

function StepEditor({ detail, step, canManage }: { detail: AutomationDetail; step: AutomationStep; canManage: boolean }) { return <article className={styles.stepCard}><div className={`${styles.stepType} ${styles[step.type]}`}>{titleCase(step.type)}</div><div className={styles.stepBody}><h3>{step.name}</h3><p>{summary(step)}</p>{canManage && !detail.lockedExecution ? <details><summary>Edit structured configuration</summary><form action={updateAutomationStepAction} className={styles.inlineForm}><input type="hidden" name="automation_id" value={detail.id}/><input type="hidden" name="step_id" value={step.id}/><label>Name<input name="name" defaultValue={step.name}/></label>{step.type === "action" ? <label>Action<select name="action_type" defaultValue={step.actionType ?? "create_task"}><option value="create_task">Create Task</option><option value="send_in_app_notification">Send In-App Notification</option></select></label> : null}<label>Configuration JSON<textarea name="config_json" rows={7} defaultValue={pretty(step.config)}/></label><button className={boardStyles.primary}>Save Step</button></form></details> : null}</div>{canManage && !detail.lockedExecution && step.type !== "trigger" ? <div className={styles.stepActions}><form action={moveAutomationStepAction}><input type="hidden" name="automation_id" value={detail.id}/><input type="hidden" name="step_id" value={step.id}/><button name="direction" value="up" aria-label="Move up"><IconArrowUp/></button><button name="direction" value="down" aria-label="Move down"><IconArrowDown/></button></form><form action={duplicateAutomationStepAction}><input type="hidden" name="automation_id" value={detail.id}/><input type="hidden" name="step_id" value={step.id}/><button>Copy</button></form><form action={deleteAutomationStepAction}><input type="hidden" name="automation_id" value={detail.id}/><input type="hidden" name="step_id" value={step.id}/><button className={styles.delete}>Delete</button></form></div> : null}</article>; }

function TriggerTab({ detail, board, canManage }: { detail: AutomationDetail; board: AutomationBoard; canManage: boolean }) { return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>Trigger</h2><p>Triggers are catalogued application events; this automation stores only its scoped configuration.</p></div></div><form action={updateAutomationTriggerAction} className={styles.settingsForm}><input type="hidden" name="automation_id" value={detail.id}/><label>Event<select name="trigger_definition_id" defaultValue={detail.triggerId ?? ""} disabled={!canManage || detail.lockedExecution}>{board.triggers.map((trigger) => <option key={trigger.id} value={trigger.id}>{titleCase(trigger.area)} · {trigger.name}</option>)}</select></label><label>Structured Configuration<textarea name="trigger_config" rows={10} defaultValue={pretty(detail.triggerConfig)} readOnly={!canManage || detail.lockedExecution}/></label>{canManage && !detail.lockedExecution ? <button className={boardStyles.primary}>Save Trigger</button> : <p className={boardStyles.safeNote}>{detail.lockedExecution ? "This trigger is owned by the legacy follow-up queue and is read-only here." : "You have read-only access."}</p>}</form></section>; }

function RunsTab({ detail, selectedRunId }: { detail: AutomationDetail; selectedRunId?: string }) { const selected = detail.runsDetail.find((run) => run.id === selectedRunId); return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>Run History</h2><p>Inputs and outputs are summarized; secrets and raw sensitive payloads are never displayed.</p></div></div>{selected ? <RunTimeline run={selected}/> : null}<div className={boardStyles.tableWrap}><table><thead><tr><th>Run</th><th>Triggered</th><th>Status</th><th>Mode</th><th>Duration</th><th>Trigger</th><th>Error</th></tr></thead><tbody>{detail.runsDetail.map((run) => <tr key={run.id}><td><Link className={boardStyles.inlineLink} href={`${ROOT}/${detail.id}?tab=runs&run=${run.id}`}>{run.id.slice(0,8)}</Link></td><td>{date(run.startedAt)}</td><td><span className={`${boardStyles.badge} ${boardStyles[run.status]}`}>{titleCase(run.status)}</span></td><td>{titleCase(run.mode)}</td><td>{run.durationMs === null ? "—" : `${run.durationMs} ms`}</td><td>{run.triggerSummary ?? titleCase(run.triggerKey)}</td><td>{run.errorSummary ?? "—"}</td></tr>)}</tbody></table></div>{!detail.runsDetail.length ? <p className={styles.emptyState}>No runs yet. This automation has not been triggered.</p> : null}</section>; }

function RunTimeline({ run }: { run: AutomationRun }) { return <div className={styles.runDetail}><header><div><b>Run {run.id.slice(0,8)}</b><span>{titleCase(run.mode)} · {date(run.startedAt)}</span></div><span className={`${boardStyles.badge} ${boardStyles[run.status]}`}>{titleCase(run.status)}</span></header><div className={styles.timeline}>{(run.steps ?? []).map((step) => <article key={step.id}><i className={step.status === "failed" ? styles.bad : step.status === "preview" ? styles.preview : styles.good}>{step.status === "failed" ? "!" : step.status === "preview" ? "○" : "✓"}</i><div><b>{step.name}</b><small>{titleCase(step.type)} · {step.durationMs === null ? "duration not recorded" : `${step.durationMs} ms`}</small><pre>{JSON.stringify(step.output, null, 2)}</pre>{step.error ? <em>{step.error}</em> : null}</div></article>)}</div></div>; }

function ErrorsTab({ detail, canManage }: { detail: AutomationDetail; canManage: boolean }) { return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>Errors</h2><p>Only safe retries are exposed. Non-idempotent actions require a new reviewed run.</p></div></div>{detail.errorsDetail.map((error) => <article className={styles.errorRow} key={error.id}><IconAlert/><div><b>{error.message}</b><small>{date(error.createdAt)} · {error.stepName ?? "Run"} · {titleCase(error.retryStatus)}</small></div>{canManage && !error.resolved ? <form action={resolveAutomationErrorAction}><input type="hidden" name="automation_id" value={detail.id}/><input type="hidden" name="error_id" value={error.id}/><button>Mark Resolved</button></form> : <span>{error.resolved ? "Resolved" : "Open"}</span>}</article>)}{!detail.errorsDetail.length ? <p className={styles.emptyState}>No automation errors have been recorded.</p> : null}</section>; }

function ActivityTab({ detail }: { detail: AutomationDetail }) { return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>Activity</h2><p>Configuration and execution lifecycle events.</p></div></div><div className={styles.activity}>{detail.activity.map((event) => <article key={event.id}><span><IconRepeat size={14}/></span><div><b>{titleCase(event.eventType)}</b><p>{event.body}</p><small>{event.actor} · {date(event.createdAt)}</small></div></article>)}{!detail.activity.length ? <p className={styles.emptyState}>No activity recorded.</p> : null}</div></section>; }

function SettingsTab({ detail, board, canManage }: { detail: AutomationDetail; board: AutomationBoard; canManage: boolean }) { return <section className={styles.panel}><div className={styles.sectionHead}><div><h2>Settings</h2><p>Ownership, classification, and measured time-saving assumptions.</p></div></div><form action={updateAutomationAction} className={styles.settingsForm}><input type="hidden" name="automation_id" value={detail.id}/><label>Name<input name="name" defaultValue={detail.name} readOnly={!canManage}/></label><label>Description<textarea name="description" rows={4} defaultValue={detail.description ?? ""} readOnly={!canManage}/></label><div className={boardStyles.two}><label>Category<select name="category" defaultValue={detail.category} disabled={!canManage}>{AUTOMATION_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Owner<select name="owner_id" defaultValue={detail.ownerId ?? ""} disabled={!canManage}><option value="">Unassigned</option>{board.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label></div><div className={boardStyles.two}><label>Tags<input name="tags" defaultValue={detail.tags.join(", ")} readOnly={!canManage}/></label><label>Manual minutes saved / run<input name="estimated_minutes_saved" type="number" min="0" defaultValue={detail.estimatedMinutesSaved ?? ""} readOnly={!canManage}/></label></div>{canManage ? <button className={boardStyles.primary}>Save Settings</button> : null}</form>{canManage && !detail.lockedExecution ? <form action={setAutomationStatusAction} className={styles.dangerZone}><input type="hidden" name="automation_id" value={detail.id}/><div><b>Archive Automation</b><p>Preserves all run history and removes the automation from active operations.</p></div><button name="status" value="archived">Archive</button></form> : null}</section>; }

export default function AutomationDetailView({ detail, board, tab, selectedRunId, canManage }: { detail: AutomationDetail; board: AutomationBoard; tab: string; selectedRunId?: string; canManage: boolean }) {
  const activeTab = tabs.includes(tab) ? tab : "overview"; const filtered = activeTab === "conditions" ? detail.steps.filter((step) => step.type === "condition" || step.type === "branch") : detail.steps.filter((step) => step.type === "action");
  return <div className={`${boardStyles.page} ${styles.page}`}><Header detail={detail} canManage={canManage}/><Kpis detail={detail}/><nav className={boardStyles.tabs}>{tabs.map((item) => <Link className={activeTab === item ? boardStyles.activeTab : ""} href={`${ROOT}/${detail.id}?tab=${item}`} key={item}>{item === "runs" ? "Run History" : titleCase(item)}</Link>)}</nav>{activeTab === "overview" ? <Flow detail={detail} canManage={canManage}/> : activeTab === "trigger" ? <TriggerTab detail={detail} board={board} canManage={canManage}/> : activeTab === "conditions" || activeTab === "actions" ? <section className={styles.panel}><div className={styles.sectionHead}><div><h2>{activeTab === "conditions" ? "Conditions & Branches" : "Actions"}</h2><p>{activeTab === "conditions" ? "Field, operator, value rules evaluated with AND / OR logic." : "Only actions backed by the current application are enabled."}</p></div></div><div className={styles.stepList}>{filtered.map((step) => <StepEditor key={step.id} detail={detail} step={step} canManage={canManage}/>)}</div>{!filtered.length ? <p className={styles.emptyState}>No {activeTab} configured.</p> : null}</section> : activeTab === "runs" ? <RunsTab detail={detail} selectedRunId={selectedRunId}/> : activeTab === "errors" ? <ErrorsTab detail={detail} canManage={canManage}/> : activeTab === "activity" ? <ActivityTab detail={detail}/> : <SettingsTab detail={detail} board={board} canManage={canManage}/>}</div>;
}
