import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { catalogPrice, type CatalogPackage } from "@/lib/catalog/types";

export const dynamic="force-dynamic"; export const metadata={title:"Packages"};
export default async function PackagesPage({searchParams}:{searchParams:Promise<{q?:string;category?:string;status?:string}>}){
  const params=await searchParams; const db=await createSupabaseServerClient(); let query=db.from("catalog_items").select("id,slug,name,catalog_category,short_description,pricing_mode,from_cents,billing_type,billing_interval,badge,featured,most_popular,status,public_enabled,public_route,frontend_locations",{count:"exact"}).eq("offer_kind","package").order("position").order("name");
  if(params.q)query=query.ilike("name",`%${params.q.replace(/[%,_]/g,"")}%`); if(params.category)query=query.eq("catalog_category",params.category); if(params.status)query=query.eq("status",params.status);
  const [{data,error,count},{data:all},{data:links,error:linksError}]=await Promise.all([query,db.from("catalog_items").select("status,billing_type,pricing_mode,featured").eq("offer_kind","package"),db.from("service_package_relationships").select("package_id")]);
  if(error)console.error("[admin/packages] package list query failed",{code:error.code,message:error.message,details:error.details,hint:error.hint});
  if(linksError)console.warn("[admin/packages] package service counts unavailable",{code:linksError.code,message:linksError.message});
  const serviceCounts=new Map<string,number>(); for(const link of links??[])serviceCounts.set(link.package_id,(serviceCounts.get(link.package_id)??0)+1);
  const total=all?.length??0,active=all?.filter(x=>x.status==="active").length??0,monthly=all?.filter(x=>x.billing_type==="recurring"&&x.status==="active").length??0,oneTime=all?.filter(x=>x.billing_type==="one_time"&&x.status==="active").length??0,custom=all?.filter(x=>x.pricing_mode==="custom_quote"&&x.status==="active").length??0,featured=all?.filter(x=>x.featured&&x.status==="active").length??0;
  return <><div className="cc-greet"><div><h1>Packages</h1><p>Manage the packages and offers displayed across the Tomorrow’s Tech AI website.</p></div><Link className="cc-btn primary" href="/admin/packages/new">+ Create Package</Link></div><div className="sv-kpis">{[["Total Packages",total],["Active Packages",active],["Monthly Packages",monthly],["One-Time Packages",oneTime],["Custom Quote",custom],["Featured",featured]].map(([label,value])=><section className="sv-kpi" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><form className="sv-toolbar"><label>Search<input className="cc-input" name="q" defaultValue={params.q}/></label><label>Category<input className="cc-input" name="category" defaultValue={params.category}/></label><label>Status<select className="cc-select" name="status" defaultValue={params.status}><option value="">All</option><option>active</option><option>draft</option><option>paused</option><option>retired</option></select></label><button className="cc-btn primary">Apply</button><Link className="cc-btn" href="/admin/packages">Reset</Link></form>{error?<div className="cc-error">Packages could not be loaded ({error.code}). Please refresh and try again.</div>:<div className="pkg-grid">{(data??[]).map(row=>{const display={pricingMode:row.pricing_mode,priceCents:row.from_cents,billingType:row.billing_type,billingInterval:row.billing_interval} as Pick<CatalogPackage,"pricingMode"|"priceCents"|"billingType"|"billingInterval">;return <article className="cc-panel sv-section pkg-card" key={row.id}><div className="pkg-card-head"><div><h2>{row.name}</h2><p className="sv-muted">{row.short_description||"No short description"}</p></div><span className={`sv-badge sv-${row.status}`}>{row.status}</span></div><strong>{catalogPrice(display)}</strong><div className="pkg-meta"><span>{row.catalog_category}</span><span>{serviceCounts.get(row.id)??0} services</span>{row.badge&&<span className="sv-badge">{row.badge}</span>}{row.featured&&<span>Featured</span>}</div><div className="pkg-usage">{(row.frontend_locations??[]).map((route:string)=><code key={route}>{route}</code>)}</div><div className="sv-actions"><Link className="cc-btn primary" href={`/admin/packages/${row.id}`}>Edit</Link>{row.public_route&&<Link className="cc-btn" href={row.public_route}>View public page</Link>}</div></article>})}</div>}<p className="sv-muted">{count??0} matching packages. Archived packages remain available to historical records but are excluded from public catalog reads.</p></>;
}
