import Link from "next/link";
import { addWorkflowApprovalAction, addWorkflowStageAction, addWorkflowTaskAction, deleteWorkflowStageAction, duplicateWorkflowAction, linkWorkflowAgentAction, linkWorkflowAutomationAction, moveWorkflowStageAction, setWorkflowStatusAction, startWorkflowRunAction, updateWorkflowAction, updateWorkflowDecisionAction } from "@/app/admin/workflow-actions";
import { IconAlert, IconArrowDown, IconArrowRight, IconArrowUp, IconBot, IconCheck, IconClock, IconLayers, IconPlus, IconRepeat, IconUsers } from "@/components/admin/cc/Icons";
import type { WorkflowBoard, WorkflowDetail } from "@/lib/workflows/types";
import { titleCase } from "@/lib/workflows/types";
import base from "./Workflows.module.css";
import styles from "./WorkflowDetail.module.css";

const ROOT = "/admin/automations/workflows";
const tabs = ["overview","builder","active-runs","stages","tasks","approvals","automations","performance","activity","settings"];
const dt = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "—";
const duration = (hours: number | null) => hours == null ? "—" : hours < 48 ? `${Math.round(hours)} hours` : `${Math.round(hours / 24 * 10) / 10} days`;

export default function WorkflowDetailView({ detail, board, tab, canManage, notice, error }: { detail: WorkflowDetail; board: WorkflowBoard; tab: string; canManage: boolean; notice?: string; error?: string }) {
  const activeRuns = detail.runsDetail.filter((run) => ["running","paused","blocked"].includes(run.status)); const completed = detail.runsDetail.filter((run) => run.completedAt); const waiting = detail.approvals.filter((approval) => approval.status === "waiting").length; const overdue = detail.tasks.filter((task) => task.due_at && new Date(String(task.due_at)) < new Date() && !["completed","canceled"].includes(String(task.status))).length + detail.approvals.filter((approval) => approval.status === "waiting" && approval.due_at && new Date(String(approval.due_at)) < new Date()).length;
  const selected = tabs.includes(tab) ? tab : "overview";
  return <div className={base.page}>
    <header className={base.header}><div><Link href={ROOT} className={styles.back}>← Workflows</Link><h1>{detail.name}</h1><div className={styles.headerBadges}><span className={base.status}>{titleCase(detail.status)}</span><span>{titleCase(detail.area)}</span><span className={`${base.badge} ${detail.health === "critical" ? base.bad : detail.health === "warning" ? base.warn : detail.health === "healthy" ? base.good : base.unknown}`}>{titleCase(detail.health)}</span><span>v{detail.version}</span></div></div><div className={base.actions}>{canManage && detail.status === "active" ? <details className={base.modal}><summary className={base.primary}><IconPlus size={14}/> Start New Run</summary><div className={base.modalCard}><h2>Start workflow run</h2><p>This run receives an immutable v{detail.version} snapshot.</p><form action={startWorkflowRunAction} className={base.form}><input type="hidden" name="workflow_id" value={detail.id}/><label>Run name<input name="name" required placeholder="ROMAR Press Onboarding"/></label><label>Owner<select name="owner_id"><option value="">Workflow owner</option>{board.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label>Client<select name="client_id"><option value="">No client</option>{board.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Project<select name="project_id"><option value="">No project</option>{board.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button className={base.primary}>Start Run</button></form></div></details> : null}{canManage ? <form action={duplicateWorkflowAction}><input type="hidden" name="workflow_id" value={detail.id}/><button className={base.button}>Duplicate</button></form> : null}{canManage ? <form action={setWorkflowStatusAction}><input type="hidden" name="workflow_id" value={detail.id}/><input type="hidden" name="status" value={detail.status === "active" ? "paused" : "active"}/><button className={base.button}>{detail.status === "active" ? "Pause" : "Activate"}</button></form> : null}</div></header>
    {notice ? <div className={base.notice}>{notice}</div> : null}{error ? <div className={base.error}>{error}</div> : null}
    <section className={base.kpis}>{[{label:"Active Runs",value:activeRuns.length,icon:IconArrowRight},{label:"Average Completion",value:detail.averageCompletion == null?"—":`${detail.averageCompletion}%`,icon:IconLayers},{label:"Average Duration",value:duration(detail.averageDurationHours),icon:IconClock},{label:"Waiting Approval",value:waiting,icon:IconUsers},{label:"Overdue Steps",value:overdue,icon:IconAlert},{label:"Completed This Month",value:completed.filter((run)=>run.completedAt && new Date(run.completedAt).getMonth()===new Date().getMonth()).length,icon:IconCheck}].map((item)=><article className={base.kpi} key={item.label}><span className={base.kpiIcon}><item.icon size={20}/></span><div><span>{item.label}</span><strong>{item.value}</strong><small>Real workflow state</small></div></article>)}</section>
    <nav className={`${base.tabs} ${styles.tabs}`}>{tabs.map((item)=><Link href={`${ROOT}/${detail.id}?tab=${item}`} className={selected===item?base.activeTab:""} key={item}>{titleCase(item)}</Link>)}</nav>
    {selected === "overview" ? <Overview detail={detail}/> : selected === "builder" ? <Builder detail={detail} board={board} canManage={canManage}/> : selected === "active-runs" ? <Runs detail={detail}/> : selected === "stages" ? <StageTable detail={detail}/> : selected === "tasks" ? <Tasks detail={detail}/> : selected === "approvals" ? <Approvals detail={detail}/> : selected === "automations" ? <Links detail={detail}/> : selected === "performance" ? <Performance detail={detail}/> : selected === "activity" ? <Activity detail={detail}/> : <Settings detail={detail} board={board} canManage={canManage}/>} 
  </div>;
}

function Overview({ detail }: { detail: WorkflowDetail }) { const active = detail.runsDetail.filter((run)=>["running","paused","blocked"].includes(run.status)); return <div className={styles.twoCol}><section className={base.panel}><div className={base.panelHead}><b>Workflow Summary</b></div><dl className={styles.definition}><div><dt>Purpose</dt><dd>{detail.purpose || detail.description || "Not documented"}</dd></div><div><dt>Area</dt><dd>{titleCase(detail.area)}</dd></div><div><dt>Owner</dt><dd>{detail.owner || "Unassigned"}</dd></div><div><dt>Status</dt><dd>{titleCase(detail.status)}</dd></div><div><dt>Created</dt><dd>{dt(detail.createdAt)}</dd></div><div><dt>Updated</dt><dd>{dt(detail.updatedAt)}</dd></div></dl></section><section className={base.panel}><div className={base.panelHead}><b>Operational State</b></div><div className={styles.metricGrid}><div><b>{active.length}</b><span>Active runs</span></div><div><b>{active.filter((run)=>run.health==="critical").length}</b><span>Blocked</span></div><div><b>{detail.approvals.filter((approval)=>approval.status==="waiting").length}</b><span>Waiting approval</span></div><div><b>{detail.runsDetail.filter((run)=>run.completedAt).length}</b><span>Completions</span></div></div></section><section className={`${base.panel} ${styles.full}`}><div className={base.panelHead}><b>Recent Runs</b></div><RunRows runs={detail.runsDetail.slice(0,8)}/></section><section className={base.panel}><div className={base.panelHead}><b>Recent Activity</b></div><Activity detail={detail}/></section><section className={base.panel}><div className={base.panelHead}><b>Process Shape</b></div><div className={styles.miniFlow}>{detail.stages.map((stage)=><span key={stage.id}>{stage.name}</span>)}</div>{!detail.stages.length?<p className={styles.muted}>No stages yet.</p>:null}</section></div>; }

function Builder({ detail, board, canManage }: { detail: WorkflowDetail; board: WorkflowBoard; canManage: boolean }) { return <><section className={styles.builder}><div className={styles.builderHead}><div><h2>Stage Builder</h2><p>Runs move left to right. Required tasks, approvals, and dependencies gate progression.</p></div>{canManage?<details className={base.modal}><summary className={base.primary}><IconPlus size={14}/> Add Stage</summary><StageForm workflowId={detail.id} owners={board.owners}/></details>:null}</div><div className={styles.flow}>{detail.stages.map((stage,index)=><div className={styles.stageWrap} key={stage.id}><article className={styles.stage}><header><span>{String(index+1).padStart(2,"0")}</span><div><b>{stage.name}</b><small>{titleCase(stage.type)}</small></div></header><p>{stage.description || titleCase(stage.completionRule)}</p><dl><div><dt>Owner</dt><dd>{stage.owner || stage.team || "Unassigned"}</dd></div><div><dt>Target</dt><dd>{duration(stage.targetHours)}</dd></div><div><dt>Tasks</dt><dd>{stage.tasks.length}</dd></div><div><dt>Approvals</dt><dd>{stage.approvals.length}</dd></div><div><dt>Automations</dt><dd>{stage.automations.length}</dd></div><div><dt>AI</dt><dd>{stage.agents.length}</dd></div></dl>{canManage?<div className={styles.stageActions}><form action={moveWorkflowStageAction}><input type="hidden" name="workflow_id" value={detail.id}/><input type="hidden" name="stage_id" value={stage.id}/><button name="direction" value="up" title="Move up"><IconArrowUp size={13}/></button><button name="direction" value="down" title="Move down"><IconArrowDown size={13}/></button></form><details><summary>Configure</summary><div className={styles.config}><StageTools workflowId={detail.id} stage={stage} stages={detail.stages} board={board}/></div></details><form action={deleteWorkflowStageAction}><input type="hidden" name="workflow_id" value={detail.id}/><input type="hidden" name="stage_id" value={stage.id}/><button title="Delete unused stage">×</button></form></div>:null}</article>{index<detail.stages.length-1?<IconArrowRight size={20}/>:null}</div>)}{!detail.stages.length?<div className={base.empty}>Add the first stage to define how work moves.</div>:null}</div></section><section className={base.panel}><div className={base.panelHead}><b>Stage Definitions</b><span>Workflow version {detail.version}</span></div><StageTable detail={detail}/></section></>; }

function StageForm({workflowId,owners}:{workflowId:string;owners:WorkflowBoard["owners"]}){return <div className={base.modalCard}><h2>Add stage</h2><form action={addWorkflowStageAction} className={base.form}><input type="hidden" name="workflow_id" value={workflowId}/><label>Name<input name="name" required placeholder="Client Approval"/></label><label>Type<select name="stage_type" defaultValue="standard">{["standard","approval","wait","decision","delivery","review","launch","completion","custom"].map(v=><option key={v} value={v}>{titleCase(v)}</option>)}</select></label><label>Owner<select name="owner_id"><option value="">Workflow owner</option>{owners.map(owner=><option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label>Team<input name="team"/></label><label>Target hours<input name="target_duration_hours" type="number" min="1"/></label><label>Completion rule<select name="completion_rule" defaultValue="all_required_tasks">{["all_required_tasks","approval_received","automation_success","manual","all_conditions"].map(v=><option key={v} value={v}>{titleCase(v)}</option>)}</select></label><label className={base.wide}>Description<textarea name="description" rows={3}/></label><label className={styles.check}><input type="checkbox" name="required" defaultChecked/>Required</label><label className={styles.check}><input type="checkbox" name="allow_skip"/>Allow manager skip</label><button className={base.primary}>Add Stage</button></form></div>}

function StageTools({workflowId,stage,stages,board}:{workflowId:string;stage:WorkflowDetail["stages"][number];stages:WorkflowDetail["stages"];board:WorkflowBoard}){return <div className={styles.tools}>
  <form action={addWorkflowTaskAction}><h3>Add task template</h3><input type="hidden" name="workflow_id" value={workflowId}/><input type="hidden" name="stage_id" value={stage.id}/><input name="title" required placeholder="Task title"/><input name="assignee" placeholder="Assignee"/><select name="task_type" defaultValue="internal">{["internal","client_intake","website","development","design","content","quality","launch","billing","automation"].map(v=><option key={v}>{v}</option>)}</select><input name="due_offset_hours" type="number" min="0" placeholder="Due offset hours"/><label><input type="checkbox" name="required" defaultChecked/> Required</label><button>Add Task</button></form>
  <form action={addWorkflowApprovalAction}><h3>Add approval</h3><input type="hidden" name="workflow_id" value={workflowId}/><input type="hidden" name="stage_id" value={stage.id}/><input name="name" required placeholder="Approval name"/><select name="approval_type">{["internal","client","manager","technical","finance","custom"].map(v=><option key={v}>{v}</option>)}</select><select name="approver_id"><option value="">Role based</option>{board.owners.map(owner=><option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><input name="due_offset_hours" type="number" min="0" placeholder="Due offset hours"/><label><input type="checkbox" name="required" defaultChecked/> Required</label><button>Add Approval</button></form>
  <form action={linkWorkflowAutomationAction}><h3>Link automation</h3><input type="hidden" name="workflow_id" value={workflowId}/><input type="hidden" name="stage_id" value={stage.id}/><select name="automation_id" required><option value="">Choose automation</option>{board.automations.filter(a=>a.status==="active").map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><select name="event_type"><option value="stage_entered">Stage Entered</option><option value="stage_completed">Stage Completed</option><option value="approval_received">Approval Received</option></select><button>Link Automation</button></form>
  <form action={linkWorkflowAgentAction}><h3>Link AI solution</h3><input type="hidden" name="workflow_id" value={workflowId}/><input type="hidden" name="stage_id" value={stage.id}/><select name="ai_solution_id" required><option value="">Choose AI solution</option>{board.agents.map(agent=><option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><input name="instructions" placeholder="Human-reviewed output purpose"/><button>Link with Review</button></form>
  {stage.type === "decision" ? <form action={updateWorkflowDecisionAction}><h3>Decision branch</h3><input type="hidden" name="workflow_id" value={workflowId}/><input type="hidden" name="stage_id" value={stage.id}/><select name="field"><option value="status">Record status</option><option value="project_type">Project type</option><option value="package">Project package</option><option value="business_type">Client business type</option><option value="state">Client state</option><option value="run_status">Run status</option></select><select name="operator">{["equals","not_equals","contains","greater_than","less_than","is_empty","is_not_empty"].map(value=><option key={value} value={value}>{titleCase(value)}</option>)}</select><input name="value" placeholder="Comparison value"/><select name="target_stage_order">{stages.filter(candidate=>candidate.order>stage.order).map(candidate=><option key={candidate.id} value={candidate.order}>{candidate.name}</option>)}</select><button>Save Decision</button></form> : null}
</div>}

function Runs({detail}:{detail:WorkflowDetail}){return <section className={base.panel}><div className={base.panelHead}><b>Active Runs</b><span>{detail.runsDetail.filter(run=>["running","paused","blocked"].includes(run.status)).length} active</span></div><RunRows runs={detail.runsDetail}/></section>}
function RunRows({runs}:{runs:WorkflowDetail["runsDetail"]}){return <div className={styles.runRows}>{runs.map(run=><Link href={`${ROOT}/${run.workflowId}/runs/${run.id}`} key={run.id}><span><b>{run.name}</b><small>{run.client || run.project || "Internal"}</small></span><span>{run.currentStage || titleCase(run.status)}</span><span><i style={{width:`${run.progress}%`}}/></span><strong>{run.progress}%</strong><em className={run.health==="critical"?styles.red:run.health==="warning"?styles.yellow:""}>{titleCase(run.health)}</em><small>{dt(run.dueAt)}</small></Link>)}{!runs.length?<div className={base.empty}>No runs have started.</div>:null}</div>}
function StageTable({detail}:{detail:WorkflowDetail}){return <div className={styles.tableScroll}><table><thead><tr><th>Order</th><th>Stage</th><th>Type</th><th>Owner</th><th>Target</th><th>Tasks</th><th>Approvals</th><th>Automations</th><th>Completion</th></tr></thead><tbody>{detail.stages.map(stage=><tr key={stage.id}><td>{stage.order+1}</td><td><b>{stage.name}</b></td><td>{titleCase(stage.type)}</td><td>{stage.owner||stage.team||"Unassigned"}</td><td>{duration(stage.targetHours)}</td><td>{stage.tasks.length}</td><td>{stage.approvals.length}</td><td>{stage.automations.length}</td><td>{titleCase(stage.completionRule)}</td></tr>)}</tbody></table></div>}
function Tasks({detail}:{detail:WorkflowDetail}){return <section className={base.panel}><div className={base.panelHead}><b>Workflow Run Tasks</b><span>Stored in Tasks</span></div><div className={styles.tableScroll}><table><thead><tr><th>Task</th><th>Run</th><th>Assignee</th><th>Status</th><th>Due</th><th>Priority</th></tr></thead><tbody>{detail.tasks.map(task=><tr key={String(task.id)}><td>{String(task.title)}</td><td>{detail.runsDetail.find(run=>run.id===task.workflow_run_id)?.name||"—"}</td><td>{String(task.owner||"Unassigned")}</td><td>{titleCase(String(task.status))}</td><td>{dt(task.due_at?String(task.due_at):null)}</td><td>{titleCase(String(task.priority))}</td></tr>)}{!detail.tasks.length?<tr><td colSpan={6} className={base.empty}>Tasks are created when a run enters a stage.</td></tr>:null}</tbody></table></div></section>}
function Approvals({detail}:{detail:WorkflowDetail}){return <section className={base.panel}><div className={base.panelHead}><b>Workflow Approvals</b><span>Human-gated</span></div><div className={styles.tableScroll}><table><thead><tr><th>Approval</th><th>Run</th><th>Type</th><th>Status</th><th>Requested</th><th>Due</th></tr></thead><tbody>{detail.approvals.map(approval=><tr key={String(approval.id)}><td>{String(approval.name)}</td><td>{detail.runsDetail.find(run=>run.id===approval.run_id)?.name||"—"}</td><td>{titleCase(String(approval.approval_type))}</td><td>{titleCase(String(approval.status))}</td><td>{dt(String(approval.requested_at))}</td><td>{dt(approval.due_at?String(approval.due_at):null)}</td></tr>)}{!detail.approvals.length?<tr><td colSpan={6} className={base.empty}>Approvals appear when their stage becomes current.</td></tr>:null}</tbody></table></div></section>}
function Links({detail}:{detail:WorkflowDetail}){const links=detail.stages.flatMap(stage=>stage.automations.map(link=>({...link,stage:stage.name})));const agents=detail.stages.flatMap(stage=>stage.agents.map(link=>({...link,stage:stage.name})));return <div className={styles.twoCol}><section className={base.panel}><div className={base.panelHead}><b>Linked Automations</b><IconRepeat size={15}/></div>{links.map(link=><div className={styles.linkRow} key={link.id}><b>{link.name}</b><span>{link.stage} · {titleCase(link.eventType)}</span></div>)}{!links.length?<p className={styles.muted}>No automations linked.</p>:null}</section><section className={base.panel}><div className={base.panelHead}><b>Linked AI Solutions</b><IconBot size={15}/></div>{agents.map(link=><div className={styles.linkRow} key={link.id}><b>{link.name}</b><span>{link.stage} · Human review required</span></div>)}{!agents.length?<p className={styles.muted}>No AI solutions linked.</p>:null}</section></div>}
function Performance({detail}:{detail:WorkflowDetail}){const completed=detail.runsDetail.filter(run=>run.completedAt);const stageStats=new Map<string,number[]>();for(const run of detail.runsDetail)for(const stage of run.stages??[])if(stage.enteredAt&&stage.completedAt){const list=stageStats.get(stage.name)??[];list.push((new Date(stage.completedAt).getTime()-new Date(stage.enteredAt).getTime())/3600000);stageStats.set(stage.name,list)}return <div className={styles.twoCol}><section className={base.panel}><div className={base.panelHead}><b>Measured Performance</b></div><div className={styles.metricGrid}><div><b>{detail.runsDetail.length}</b><span>Runs</span></div><div><b>{detail.runsDetail.length?Math.round(completed.length/detail.runsDetail.length*100):"—"}{detail.runsDetail.length?"%":""}</b><span>Completion rate</span></div><div><b>{duration(detail.averageDurationHours)}</b><span>Average duration</span></div><div><b>{detail.runsDetail.filter(run=>run.health==="critical").length}</b><span>Blocked runs</span></div></div></section><section className={base.panel}><div className={base.panelHead}><b>Stage Duration</b></div>{[...stageStats].map(([name,values])=><div className={styles.durationRow} key={name}><span>{name}</span><b>{duration(values.reduce((a,b)=>a+b,0)/values.length)}</b><small>{values.length} samples</small></div>)}{!stageStats.size?<p className={styles.muted}>Stage timing appears after stages complete.</p>:null}</section></div>}
function Activity({detail}:{detail:WorkflowDetail}){return <div className={styles.timeline}>{detail.activity.map(event=><div key={event.id}><i/><span><b>{event.body||titleCase(event.eventType)}</b><small>{event.actor} · {dt(event.createdAt)}</small></span></div>)}{!detail.activity.length?<p className={styles.muted}>No activity yet.</p>:null}</div>}
function Settings({detail,board,canManage}:{detail:WorkflowDetail;board:WorkflowBoard;canManage:boolean}){return <section className={base.panel}><div className={base.panelHead}><b>Workflow Settings</b><span>Changes create v{detail.version+1}</span></div>{canManage?<form action={updateWorkflowAction} className={`${base.form} ${styles.settings}`}><input type="hidden" name="workflow_id" value={detail.id}/><label>Name<input name="name" defaultValue={detail.name} required/></label><label>Area<select name="area" defaultValue={detail.area}>{["sales","clients","projects","marketing","finance","software","system"].map(v=><option key={v}>{v}</option>)}</select></label><label>Owner<select name="owner_id" defaultValue={detail.ownerId??""}><option value="">Unassigned</option>{board.owners.map(owner=><option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label>Target hours<input name="target_duration_hours" type="number" min="1" defaultValue={detail.targetHours??""}/></label><label className={base.wide}>Description<textarea name="description" rows={3} defaultValue={detail.description??""}/></label><label className={base.wide}>Purpose<textarea name="purpose" rows={3} defaultValue={detail.purpose??""}/></label><button className={base.primary}>Save New Version</button></form>:<p className={styles.muted}>You have read-only access.</p>}</section>}
