import Link from "next/link";
import { createWorkflowAction, useWorkflowTemplateAction } from "@/app/admin/workflow-actions";
import { IconAlert, IconArrowRight, IconBriefcase, IconCheck, IconClock, IconGrid, IconLayers, IconPlus, IconSearch, IconUsers } from "@/components/admin/cc/Icons";
import type { WorkflowBoard, WorkflowFilters, WorkflowHealth } from "@/lib/workflows/types";
import { titleCase } from "@/lib/workflows/types";
import styles from "./Workflows.module.css";

const ROOT = "/admin/automations/workflows";
const hours = (value: number | null) => value == null ? "—" : value < 48 ? `${Math.round(value)}h` : `${Math.round(value / 24 * 10) / 10}d`;
const date = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(value));
const qs = (filters: WorkflowFilters, patch: Record<string, string>) => { const query = new URLSearchParams(); for (const [key, value] of Object.entries({ ...filters, ...patch })) if (value && value !== "all" && value !== "table") query.set(key, String(value)); const result = query.toString(); return result ? `${ROOT}?${result}` : ROOT; };
const healthClass = (value: WorkflowHealth) => value === "healthy" ? styles.good : value === "warning" ? styles.warn : value === "critical" ? styles.bad : styles.unknown;

export default function WorkflowBoardView({ board, filters, canManage, notice, error }: { board: WorkflowBoard; filters: WorkflowFilters; canManage: boolean; notice?: string; error?: string }) {
  const healthCounts = { healthy: 0, warning: 0, critical: 0, unknown: 0 }; for (const workflow of board.workflows) healthCounts[workflow.health] += 1;
  return <div className={styles.page}>
    <header className={styles.header}>
      <div><h1>Workflows</h1><p>Manage complete business processes, stages, approvals, owners, dependencies, and active runs from one place.</p></div>
      <div className={styles.actions}>
        {canManage ? <details className={styles.modal}><summary className={styles.primary}><IconPlus size={15}/> New Workflow</summary><div className={styles.modalCard}><h2>Create workflow</h2><p>Start with the process basics. Build stages next, then activate.</p><form action={createWorkflowAction} className={styles.form}><label>Name<input name="name" required placeholder="New Client Onboarding"/></label><label>Area<select name="area" defaultValue="clients"><option value="sales">Sales</option><option value="clients">Clients</option><option value="projects">Projects</option><option value="marketing">Marketing</option><option value="finance">Finance</option><option value="software">Software</option><option value="system">System</option></select></label><label className={styles.wide}>Description<textarea name="description" rows={3}/></label><label>Owner<select name="owner_id"><option value="">Current admin</option>{board.owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.name}</option>)}</select></label><label>Target hours<input name="target_duration_hours" type="number" min="1"/></label><label>Priority<select name="priority" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Tags<input name="tags" placeholder="onboarding, client"/></label><button className={styles.primary} type="submit">Create Draft <IconArrowRight size={14}/></button></form></div></details> : null}
        <Link className={styles.button} href={qs(filters, { view: "templates" })}>Templates</Link><Link className={styles.button} href={qs(filters, { view: "runs" })}>Active Runs</Link>
      </div>
    </header>
    {notice ? <div className={styles.notice}>{notice}</div> : null}{error ? <div className={styles.error}>{error}</div> : null}
    <section className={styles.kpis}>
      {[{ label: "Active Workflows", value: board.kpis.activeWorkflows, icon: IconLayers, tone: "blue" }, { label: "Running Instances", value: board.kpis.runningInstances, icon: IconArrowRight, tone: "blue" }, { label: "Waiting Approval", value: board.kpis.waitingApproval, icon: IconUsers, tone: "yellow" }, { label: "Overdue Steps", value: board.kpis.overdueSteps, icon: IconClock, tone: "red" }, { label: "Completed This Month", value: board.kpis.completedThisMonth, icon: IconCheck, tone: "green" }, { label: "Needs Attention", value: board.kpis.needsAttention, icon: IconAlert, tone: "red" }].map((kpi) => <article className={styles.kpi} key={kpi.label}><span className={`${styles.kpiIcon} ${styles[kpi.tone]}`}><kpi.icon size={22}/></span><div><span>{kpi.label}</span><strong>{kpi.value}</strong><small>Live operational data</small></div></article>)}
    </section>
    <section className={styles.attention}>
      <div className={styles.sectionTitle}><span><IconAlert size={18}/> <b>Needs Attention</b> <small>{board.attention.length ? `${board.attention.length} items require attention` : "No active issues"}</small></span><Link href={qs(filters, { health: "warning" })}>View All <IconArrowRight size={13}/></Link></div>
      <div className={styles.attentionItems}>{board.attention.length ? board.attention.slice(0, 3).map((item) => <Link href={item.href} key={item.id}><span className={`${styles.dot} ${item.severity === "critical" ? styles.badBg : item.severity === "warning" ? styles.warnBg : styles.blueBg}`}/><span><b>{item.title}</b><small>{item.detail}</small></span></Link>) : <div className={styles.clear}><IconCheck size={16}/> Nothing is blocked or overdue.</div>}</div>
    </section>
    <nav className={styles.tabs}>{["all", "sales", "clients", "projects", "marketing", "finance", "software", "system"].map((area) => <Link key={area} className={(filters.area ?? "all") === area ? styles.activeTab : ""} href={qs(filters, { area })}>{area === "all" ? "All Workflows" : titleCase(area)}</Link>)}</nav>
    <div className={styles.layout}>
      <main className={styles.main}>
        <form method="get" className={styles.filters}><label className={styles.search}><IconSearch size={15}/><input name="q" defaultValue={filters.q} placeholder="Search workflows..."/></label><select name="status" defaultValue={filters.status ?? ""}><option value="">Status</option>{["draft","active","paused","deprecated"].map((value) => <option key={value}>{value}</option>)}</select><select name="area" defaultValue={filters.area ?? "all"}><option value="all">All areas</option>{["sales","clients","projects","marketing","finance","software","system"].map((value) => <option key={value}>{value}</option>)}</select><select name="owner" defaultValue={filters.owner ?? ""}><option value="">Owner</option>{board.owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><select name="health" defaultValue={filters.health ?? ""}><option value="">Health</option>{["healthy","warning","critical","unknown"].map((value) => <option key={value}>{value}</option>)}</select><select name="sort" defaultValue={filters.sort}><option value="updated">Last Updated</option><option value="active">Most Active</option><option value="completion">Lowest Completion</option><option value="duration">Longest Duration</option><option value="name">Name</option></select><input type="hidden" name="view" value={filters.view}/><button type="submit" className={styles.button}>Apply</button><span className={styles.viewToggle}><Link className={filters.view === "table" ? styles.selected : ""} href={qs(filters, { view: "table" })}>Table</Link><Link className={filters.view === "cards" ? styles.selected : ""} href={qs(filters, { view: "cards" })}>Cards</Link></span></form>
        {filters.view === "runs" ? <Runs runs={board.runs}/> : filters.view === "templates" ? <Templates board={board} canManage={canManage}/> : filters.view === "cards" ? <div className={styles.cards}>{board.workflows.map((workflow) => <WorkflowCard workflow={workflow} key={workflow.id}/>)}</div> : <WorkflowTable board={board}/>} 
        {filters.view !== "templates" ? <Templates board={board} canManage={canManage}/> : null}
      </main>
      <aside className={styles.rail}>
        <section className={styles.panel}><div className={styles.panelHead}><b>Workflow Health</b><Link href={qs(filters, { health: "warning" })}>View Details</Link></div><div className={styles.health}><div className={styles.donut} style={{ background: board.workflows.length ? `conic-gradient(#0fd8a2 0 ${healthCounts.healthy / board.workflows.length * 100}%,#ffd126 0 ${(healthCounts.healthy + healthCounts.warning) / board.workflows.length * 100}%,#ff4364 0 ${(healthCounts.healthy + healthCounts.warning + healthCounts.critical) / board.workflows.length * 100}%,#53657a 0)` : undefined }}><span><b>{board.workflows.length}</b><small>Total</small></span></div><div className={styles.legend}><span><i className={styles.goodBg}/>Healthy <b>{healthCounts.healthy}</b></span><span><i className={styles.warnBg}/>Warnings <b>{healthCounts.warning}</b></span><span><i className={styles.badBg}/>Critical <b>{healthCounts.critical}</b></span><span><i className={styles.grayBg}/>Unknown <b>{healthCounts.unknown}</b></span></div></div></section>
        <section className={styles.panel}><div className={styles.panelHead}><b>Active Runs</b><Link href={qs(filters, { view: "runs" })}>View All</Link></div><div className={styles.stack}>{board.runs.slice(0, 5).map((run) => <Link href={`${ROOT}/${run.workflowId}/runs/${run.id}`} key={run.id}><span><b>{run.name}</b><small>{run.progress}% · {run.currentStage ?? titleCase(run.status)}</small></span><div className={styles.miniProgress}><i style={{ width: `${run.progress}%` }}/></div></Link>)}{!board.runs.length ? <small>No workflow runs have started.</small> : null}</div></section>
        <section className={styles.panel}><div className={styles.panelHead}><b>Top Bottlenecks</b></div><div className={styles.stack}>{board.bottlenecks.map((item) => <div className={styles.bottleneck} key={item.stage}><span><b>{item.stage}</b><small>Average {hours(item.averageHours)}{item.targetHours ? ` · target ${hours(item.targetHours)}` : ""}</small></span><em>{item.runs} runs</em></div>)}{!board.bottlenecks.length ? <small>No completed stage timing exists yet.</small> : null}</div></section>
        <section className={styles.panel}><div className={styles.panelHead}><b>Recent Activity</b></div><div className={styles.activity}>{board.activity.slice(0, 6).map((event) => <div key={event.id}><i/><span><b>{event.body ?? titleCase(event.eventType)}</b><small>{event.actor} · {date(event.createdAt)}</small></span></div>)}{!board.activity.length ? <small>No workflow activity yet.</small> : null}</div></section>
      </aside>
    </div>
  </div>;
}

function WorkflowTable({ board }: { board: WorkflowBoard }) { return <div className={styles.tableWrap}><table><thead><tr><th>Workflow</th><th>Area</th><th>Active Runs</th><th>Completion</th><th>Avg Duration</th><th>Health</th><th>Status</th><th>Owner</th><th>Actions</th></tr></thead><tbody>{board.workflows.map((workflow) => <tr key={workflow.id}><td><Link className={styles.workflowName} href={`${ROOT}/${workflow.id}`}><span><IconLayers size={18}/></span><b>{workflow.name}<small>{workflow.description || `${workflow.stageCount} stage process`}</small></b></Link></td><td>{titleCase(workflow.area)}</td><td>{workflow.activeRuns}</td><td><div className={styles.progress}><span style={{ width: `${workflow.averageCompletion ?? 0}%` }}/></div><small>{workflow.averageCompletion == null ? "No active runs" : `${workflow.averageCompletion}%`}</small></td><td>{hours(workflow.averageDurationHours)}</td><td><span className={`${styles.badge} ${healthClass(workflow.health)}`}><i/>{titleCase(workflow.health)}</span></td><td><span className={styles.status}>{titleCase(workflow.status)}</span></td><td>{workflow.owner ?? "Unassigned"}</td><td><Link href={`${ROOT}/${workflow.id}`}>View</Link></td></tr>)}{!board.workflows.length ? <tr><td colSpan={9} className={styles.empty}>No workflows match these filters. Create one or use an existing task template.</td></tr> : null}</tbody></table></div>; }
function WorkflowCard({ workflow }: { workflow: WorkflowBoard["workflows"][number] }) { return <Link href={`${ROOT}/${workflow.id}`} className={styles.workflowCard}><span className={styles.cardIcon}><IconLayers size={20}/></span><div><b>{workflow.name}</b><p>{workflow.description || "No description yet."}</p><div><span>{workflow.stageCount} stages</span><span>{workflow.activeRuns} active</span><span className={healthClass(workflow.health)}>{titleCase(workflow.health)}</span></div><div className={styles.progress}><span style={{ width: `${workflow.averageCompletion ?? 0}%` }}/></div></div></Link>; }
function Runs({ runs }: { runs: WorkflowBoard["runs"] }) { return <section className={styles.panel}><div className={styles.panelHead}><b>Active Workflow Runs</b><span>{runs.length} active</span></div><div className={styles.runList}>{runs.map((run) => <Link href={`${ROOT}/${run.workflowId}/runs/${run.id}`} key={run.id}><span><IconBriefcase size={17}/><b>{run.name}</b><small>{run.workflowName}</small></span><span>{run.currentStage ?? "No current stage"}</span><span><div className={styles.progress}><i style={{ width: `${run.progress}%` }}/></div>{run.progress}%</span><span className={`${styles.badge} ${healthClass(run.health)}`}>{titleCase(run.health)}</span></Link>)}{!runs.length ? <div className={styles.empty}>No active runs. Activate a workflow and start its first run.</div> : null}</div></section>; }
function Templates({ board, canManage }: { board: WorkflowBoard; canManage: boolean }) { return <section className={styles.templates}><div className={styles.templatesHead}><div><h2>Workflow Templates</h2><p>Reusable processes backed by existing task blueprints.</p></div><span>{board.templates.length} available</span></div><div className={styles.templateGrid}>{board.templates.map((template) => <article key={template.id}><span className={styles.cardIcon}><IconGrid size={18}/></span><div><b>{template.name}</b><small>{titleCase(template.area)} · {template.stageCount} stages</small><p>{template.description}</p></div>{canManage ? <form action={useWorkflowTemplateAction}><input type="hidden" name="template_id" value={template.id}/><button className={styles.outline} type="submit">Use Template <IconArrowRight size={13}/></button></form> : null}</article>)}{!board.templates.length ? <div className={styles.empty}>No workflow templates are configured.</div> : null}</div></section>; }
