import Link from "next/link";
import { advanceWorkflowRunAction, decideWorkflowApprovalAction, setWorkflowRunStatusAction } from "@/app/admin/workflow-actions";
import { IconAlert, IconArrowRight, IconCheck, IconClock, IconLayers, IconUsers } from "@/components/admin/cc/Icons";
import type { WorkflowRun } from "@/lib/workflows/types";
import { titleCase } from "@/lib/workflows/types";
import base from "./Workflows.module.css";
import styles from "./WorkflowDetail.module.css";
import runStyles from "./WorkflowRun.module.css";

const ROOT = "/admin/automations/workflows";
const dateTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "—";
const days = (from: string, to: string | null) => Math.max(0, Math.ceil((new Date(to ?? Date.now()).getTime() - new Date(from).getTime()) / 86_400_000));

export default function WorkflowRunDetail({ data, canManage, notice, error }: { data: { run: WorkflowRun; tasks: Array<Record<string, unknown>>; approvals: Array<Record<string, unknown>>; activity: Array<Record<string, unknown>> }; canManage: boolean; notice?: string; error?: string }) {
  const { run, tasks, approvals, activity } = data; const overdue = tasks.filter((task) => task.due_at && new Date(String(task.due_at)) < new Date() && !["completed","canceled"].includes(String(task.status))).length; const waiting = approvals.filter((approval) => approval.status === "waiting").length; const completedStages = run.stages?.filter((stage) => ["completed","skipped"].includes(stage.status)).length ?? 0;
  return <div className={base.page}>
    <header className={base.header}><div><Link href={`${ROOT}/${run.workflowId}?tab=active-runs`} className={styles.back}>← {run.workflowName}</Link><h1>{run.name}</h1><div className={styles.headerBadges}><span>{run.client || run.project || "Internal run"}</span><span>{run.currentStage || titleCase(run.status)}</span><span className={`${base.badge} ${run.health === "critical" ? base.bad : run.health === "warning" ? base.warn : base.good}`}>{titleCase(run.health)}</span></div></div>{canManage?<div className={base.actions}>{["running","blocked"].includes(run.status)?<form action={advanceWorkflowRunAction}><input type="hidden" name="workflow_id" value={run.workflowId}/><input type="hidden" name="run_id" value={run.id}/><button className={base.primary}>Advance Stage <IconArrowRight size={14}/></button></form>:null}<form action={setWorkflowRunStatusAction}><input type="hidden" name="workflow_id" value={run.workflowId}/><input type="hidden" name="run_id" value={run.id}/><input type="hidden" name="status" value={run.status === "paused" ? "running" : "paused"}/><button className={base.button}>{run.status === "paused" ? "Resume" : "Pause"}</button></form></div>:null}</header>
    {notice?<div className={base.notice}>{notice}</div>:null}{error?<div className={base.error}>{error}</div>:null}
    <section className={base.kpis}>{[{label:"Progress",value:`${run.progress}%`,icon:IconLayers},{label:"Days Running",value:days(run.startedAt,run.completedAt),icon:IconClock},{label:"Overdue Steps",value:overdue,icon:IconAlert},{label:"Open Tasks",value:tasks.filter(task=>!["completed","canceled"].includes(String(task.status))).length,icon:IconCheck},{label:"Waiting Approvals",value:waiting,icon:IconUsers},{label:"Completed Stages",value:completedStages,icon:IconCheck}].map(item=><article className={base.kpi} key={item.label}><span className={base.kpiIcon}><item.icon size={20}/></span><div><span>{item.label}</span><strong>{item.value}</strong><small>Live run state</small></div></article>)}</section>
    <section className={`${base.panel} ${runStyles.timelinePanel}`}><div className={base.panelHead}><b>Stage Timeline</b><span>Started {dateTime(run.startedAt)}</span></div><div className={runStyles.stageTimeline}>{run.stages?.map((stage,index)=><div className={`${runStyles.timelineStage} ${runStyles[stage.status] ?? ""}`} key={stage.id}><span>{stage.status === "completed" ? <IconCheck size={15}/> : index+1}</span><div><b>{stage.name}</b><small>{titleCase(stage.status)}</small><em>{stage.blockedReason || (stage.enteredAt ? `${dateTime(stage.enteredAt)}${stage.completedAt ? ` → ${dateTime(stage.completedAt)}` : ""}` : "Not started")}</em></div></div>)}</div></section>
    <div className={styles.twoCol}><section className={base.panel}><div className={base.panelHead}><b>Tasks</b><Link href="/admin/tasks">Open Tasks</Link></div><div className={runStyles.rows}>{tasks.map(task=><div key={String(task.id)}><span><b>{String(task.title)}</b><small>{String(task.owner||"Unassigned")} · {dateTime(task.due_at?String(task.due_at):null)}</small></span><em>{titleCase(String(task.status))}</em></div>)}{!tasks.length?<p className={styles.muted}>No tasks in the current or completed stages.</p>:null}</div></section><section className={base.panel}><div className={base.panelHead}><b>Approvals</b><span>{waiting} waiting</span></div><div className={runStyles.rows}>{approvals.map(approval=><div className={runStyles.approval} key={String(approval.id)}><span><b>{String(approval.name)}</b><small>{titleCase(String(approval.approval_type))} · due {dateTime(approval.due_at?String(approval.due_at):null)}</small></span><em>{titleCase(String(approval.status))}</em>{approval.status==="waiting"&&canManage?<form action={decideWorkflowApprovalAction}><input type="hidden" name="workflow_id" value={run.workflowId}/><input type="hidden" name="run_id" value={run.id}/><input type="hidden" name="approval_id" value={String(approval.id)}/><input name="comments" placeholder="Decision comments"/><button name="status" value="approved">Approve</button><button name="status" value="changes_requested">Changes</button><button name="status" value="rejected">Reject</button></form>:null}</div>)}{!approvals.length?<p className={styles.muted}>No approvals requested for entered stages.</p>:null}</div></section><section className={`${base.panel} ${styles.full}`}><div className={base.panelHead}><b>Run Activity</b></div><div className={styles.timeline}>{activity.map(event=><div key={String(event.id)}><i/><span><b>{String(event.body||titleCase(String(event.event_type)))}</b><small>{String(event.actor)} · {dateTime(String(event.created_at))}</small></span></div>)}</div></section></div>
  </div>;
}
