import Image from "next/image";
import Link from "next/link";
import { IconAiChip, IconArrowRight, IconBadgeCheck, IconBot, IconCalendar, IconCart, IconChart, IconCode, IconDashboard, IconMail, IconMonitor, IconNetwork, IconRocket, IconUsers } from "@/components/Icons";
import styles from "./runBusiness.module.css";

const features = [
  {Icon:IconDashboard,title:"Dashboard",copy:"See everything at a glance",tone:"blue"},{Icon:IconUsers,title:"Leads",copy:"Capture and track leads",tone:"green"},{Icon:IconUsers,title:"CRM",copy:"Manage customers",tone:"violet"},{Icon:IconNetwork,title:"Pipeline",copy:"Track sales & opportunities",tone:"amber"},{Icon:IconCalendar,title:"Projects",copy:"Jobs, tasks and progress",tone:"blue"},
  {Icon:IconCalendar,title:"Calendar",copy:"Schedule and manage",tone:"blue"},{Icon:IconCart,title:"Orders",copy:"Products, inventory, POs",tone:"amber"},{Icon:IconMail,title:"Documents",copy:"Contracts, files, photos",tone:"blue"},{Icon:IconChart,title:"Analytics",copy:"Real-time insights",tone:"green"},{Icon:IconBot,title:"AI Assistant",copy:"Work smarter, faster",tone:"blue"},
];
const workflow = [{Icon:IconUsers,label:"Lead"},{Icon:IconMail,label:"Contact"},{Icon:IconMail,label:"Estimate"},{Icon:IconUsers,label:"Customer"},{Icon:IconMonitor,label:"Project"},{Icon:IconBadgeCheck,label:"Completed"},{Icon:IconMail,label:"Invoice"},{Icon:IconNetwork,label:"Follow-Up"}];
const industries = [
  {name:"Contractors & Builders",image:"/industries/contractors-home-services.webp",position:"30% center"},{name:"HVAC Services",image:"/industries/contractors-home-services.webp",position:"72% center"},{name:"Pool Companies",image:"/work/clearwater.webp"},{name:"Telecom / Tower Companies",image:"/industries/professional-services.webp"},{name:"Automotive",image:"/work/tomorrowstek.webp"},{name:"Professional Services",image:"/industries/professional-services.webp",position:"25% center"},{name:"Publishers & Authors",image:"/work/darktides.webp"},
];

function SectionHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}) { return <header className={styles.sectionHead}><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2><p>{copy}</p></header>; }

export function CommandCenterFeatures() { return <section id="command-center" className={styles.section}><SectionHead eyebrow="One Command Center" title="Everything Your Business Needs. Connected." copy="Stop jumping between a dozen different apps. Your team, your data, your customers and your operations — all in one powerful platform."/><div className={styles.featureGrid}>{features.map(({Icon,title,copy,tone})=><article className={styles.feature} key={title}><span data-tone={tone}><Icon size={22}/></span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>; }

export function BusinessWorkflow() { return <section className={`${styles.section} ${styles.workflowSection}`}><SectionHead eyebrow="From Lead to Paid" title="Track Every Step of Your Business." copy="A complete workflow from the first lead to long-term customer relationships."/><div className={styles.workflow}>{workflow.map(({Icon,label},i)=><div className={styles.workflowPair} key={label}><article><Icon size={23}/><b>{label}</b></article>{i<workflow.length-1&&<IconArrowRight className={styles.flowArrow} size={20}/>}</div>)}</div></section>; }

export function IndustrySolutions() { return <section className={styles.section}><SectionHead eyebrow="Built for Your Industry" title="Different Businesses. Same Powerful Platform." copy="We customize your system to match the way your business actually works."/><div className={styles.industryGrid}>{industries.map(item=><article className={styles.industry} key={item.name}><Image src={item.image} alt="" fill sizes="(max-width: 700px) 72vw, 15vw" style={{objectPosition:item.position}}/><div/><h3>{item.name}</h3></article>)}</div></section>; }

export function AIBusinessSection() { const list=["Answer questions about your business","Automate follow-ups and reminders","Create proposals, emails and reports","Identify opportunities","Detect issues before they become problems","Save hours of manual work"]; return <section className={styles.aiSection}><div className={styles.aiVisual} aria-hidden="true"><div className={`${styles.circuit} ${styles.c1}`}/><div className={`${styles.circuit} ${styles.c2}`}/><div className={`${styles.circuit} ${styles.c3}`}/><div className={styles.aiCore}><IconAiChip size={74}/><span>AI</span></div><div className={styles.aiOrbit}/></div><div className={styles.aiCopy}><span className={styles.eyebrow}>Put AI Inside Your Business</span><h2>Work Smarter With AI</h2><p>Your AI assistant can summarize activity, draft customer communications, identify overdue work, surface new opportunities and even execute approved workflows — all trained on your business data.</p><div className={styles.aiList}>{list.map(item=><span key={item}><IconBadgeCheck size={18}/>{item}</span>)}</div></div></section>; }

export function RunBusinessCTA() { return <section className={styles.finalCta}><div><span className={styles.eyebrow}>Your Business. Your System.</span><h2>Tell Us How Your Business Works.<br/><em>We’ll Build the System to Run It.</em></h2><p>No generic software package. No pile of disconnected apps. One platform built for your operation.</p><div className={styles.actions}><Link href="/contact?service=run-your-business&plan=run-your-business-custom" className={styles.primary}>Build My System <IconArrowRight size={17}/></Link><a href="https://cal.com/tomorrowstechai/discovery" className={styles.secondary}>Schedule a Demo</a></div><div className={styles.finalTrust}>{[{Icon:IconCode,label:"Custom Development"},{Icon:IconRocket,label:"Fast Implementation"},{Icon:IconUsers,label:"Ongoing Support"},{Icon:IconChart,label:"Built to Scale"}].map(({Icon,label})=><span key={label}><Icon size={18}/>{label}</span>)}</div></div><aside>Operational Chaos<br/><IconArrowRight size={25}/><br/><em>Operational Clarity</em></aside></section>; }
