import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { randomUUID } from 'node:crypto';
import { createSupabaseServerClient, getAdminUser } from '@/lib/supabase/server';
import { loadClientServices } from '@/lib/services/queries';
import { isUuid, money, marginLabel, priceLabel } from '@/lib/services/pricing';
import { BILLING_LABELS, type Automation, type Service, type Sale } from '@/lib/services/types';
import { ActionForm, ServiceEditor, ServiceModal, StatusAction } from '@/components/admin/cc/services/ServiceForms';
import ClientAssignments from '@/components/admin/cc/services/ClientAssignments';
import ServiceAdCreative from '@/components/admin/cc/services/ServiceAdCreative';
import { assignClient, savePackage, removePackage, saveAutomation } from '@/app/admin/service-actions';

export const dynamic = 'force-dynamic';
const TABS = ['Overview','Creative','Pricing','Packages','Clients','Sales','Automations','Settings'];
export default async function ServiceDetail({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string|undefined>> }) {
  const session = await getAdminUser(); if (!session) redirect('/admin/login');
  const { id } = await params; if (!isUuid(id)) notFound();
  const canManage = ['owner','admin'].includes(session.admin.role); const db = await createSupabaseServerClient();
  const [{ data, error }, { data: creative, error: creativeError }] = await Promise.all([
    db.from('service_directory').select('*').eq('id',id).maybeSingle(),
    db.from('catalog_items').select('ad_image_path').eq('id',id).maybeSingle(),
  ]);
  if (error || creativeError) throw new Error('Unable to load service.'); if (!data || !creative) notFound(); const s = data as Service;
  const query = await searchParams; const tab = TABS.find(t => t.toLowerCase() === query.tab) ?? 'Overview';
  const page = Math.max(1,Math.min(100000,parseInt(query.page ?? '1') || 1));
  let content: React.ReactNode;
  if (tab === 'Overview') {
    const events = await db.from('service_events').select('id,body,actor,created_at').eq('service_id',id).order('created_at',{ascending:false}).limit(15);
    if (events.error) throw new Error('Unable to load activity.');
    const facts = { 'Billing Type': BILLING_LABELS[s.billing_type], 'Current Price': priceLabel(s), ...(canManage ? { 'Internal Cost': s.internal_cost_cents === null ? 'Not set' : money(s.internal_cost_cents), 'Margin':marginLabel(s.margin) } : {}), 'MRR':money(s.mrr_cents), 'Total Revenue':money(s.revenue_cents), 'Active Clients':s.active_clients, 'Total Sales':s.sales_count, 'Created':new Date(s.created_at).toLocaleDateString('en-US'), 'Last Updated':new Date(s.updated_at).toLocaleDateString('en-US') };
    content = <><section className="cc-panel sv-section"><h2>Service overview</h2><p className="sv-muted">{s.description || 'No description yet.'}</p><dl className="sv-definition">{Object.entries(facts).map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="cc-panel sv-section"><h2>Recent activity</h2>{events.data?.length ? events.data.map(e => <p className="sv-muted" key={e.id}>{e.body}<br />{e.actor} · {new Date(e.created_at).toLocaleString('en-US')}</p>) : <p className="sv-muted">No activity recorded yet.</p>}</section></>;
  } else if (tab === 'Creative') {
    content = <section className="cc-panel sv-section"><h2>Ad creative</h2><p className="sv-muted">Keep one current, ready-to-use promotional image with this service. Replacing it leaves pricing, proposals, invoices, and client history unchanged.</p><ServiceAdCreative serviceId={id} serviceName={s.name} imagePath={creative.ad_image_path} version={s.updated_at} canManage={canManage} /></section>;
  } else if (tab === 'Pricing' || tab === 'Settings') {
    const history = tab === 'Pricing' ? await db.from('service_price_history').select('*').eq('service_id',id).order('created_at',{ascending:false}).limit(25) : null;
    if (history?.error) throw new Error('Unable to load price history.');
    content = <><section className="cc-panel sv-section">{canManage ? <ServiceEditor service={s} /> : <p className="sv-muted">Your role can view service prices. Editing and internal costs require an owner or admin.</p>}</section>{history && <section className="cc-panel sv-section"><h2>Price history</h2>{history.data?.length ? history.data.map(h => <p key={h.id} className="sv-muted">{money(h.price_cents)} · {BILLING_LABELS[h.billing_type]} · Setup {money(h.setup_fee_cents)} · {new Date(h.created_at).toLocaleString('en-US')} · {h.actor}</p>) : <p className="sv-muted">Future price changes will be recorded here. Historical transaction prices remain unchanged.</p>}</section>}{canManage && tab==='Settings' && <section className="cc-panel sv-section"><h2>Service status</h2><p className="sv-muted">Retirement removes new-sale availability while preserving client and financial history.</p><div className="sv-actions"><StatusAction service={s} status={s.status==='active' ? 'paused':'active'} />{s.status!=='retired' && <StatusAction service={s} status="retired" />}</div></section>}</>;
  } else if (tab === 'Packages') {
    const [links, options] = await Promise.all([db.from('service_package_relationships').select('*,package:catalog_items!package_id(name)').eq('service_id',id),db.from('catalog_items').select('id,name').neq('id',id).order('name').limit(1000)]);
    if (links.error || options.error) throw new Error('Unable to load packages.');
    content = <><section className="cc-panel sv-section"><h2>Package relationships</h2>{['included','addon'].map(kind => <div key={kind}><h3>{kind==='included' ? 'Included In Packages':'Optional Add-On For Packages'}</h3>{links.data?.filter(r=>r.relationship_type===kind).length ? links.data.filter(r=>r.relationship_type===kind).map(r => <div key={r.id} className="sv-pager"><div><Link className="cc-link" href={`/admin/services/${r.package_id}`}>{r.package?.name}</Link> · Quantity {r.quantity}<p className="sv-muted">{r.notes}</p></div>{canManage && <ActionForm action={removePackage} label="Remove" confirm="Remove this package relationship?"><input type="hidden" name="id" value={r.id} /><input type="hidden" name="service_id" value={id} /></ActionForm>}</div>) : <p className="sv-muted">No relationships yet.</p>}</div>)}</section>{canManage && <section className="cc-panel sv-section"><h2>Add or update relationship</h2><ActionForm action={savePackage}><input type="hidden" name="service_id" value={id} /><div className="sv-fields"><label>Package<select name="package_id" required className="cc-select"><option value="">Select an existing Catalog package</option>{options.data?.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Relationship<select name="relationship_type" className="cc-select"><option value="included">Included</option><option value="addon">Optional add-on</option></select></label><label>Quantity / Limit<input type="number" name="quantity" className="cc-input" min="0.01" step="0.01" defaultValue="1" required /></label><label>Notes<input name="notes" className="cc-input" placeholder="For example, up to 10 pages" /></label></div></ActionForm></section>}</>;
  } else if (tab === 'Clients') {
    const [assignments, clients] = await Promise.all([loadClientServices(db,{serviceId:id},page), canManage ? db.from('customers').select('id,name,business_name').order('business_name').limit(1000) : Promise.resolve({data:[],error:null})]);
    if (clients.error) throw new Error('Unable to load clients.');
    content = <><section className="cc-panel sv-section"><h2>Clients using this service</h2><ClientAssignments rows={assignments.rows} canManage={canManage} /><div className="sv-pager"><span>{assignments.count} assignments</span>{page>1 && <Link href={`?tab=clients&page=${page-1}`}>Previous</Link>}{page*25<assignments.count && <Link href={`?tab=clients&page=${page+1}`}>Next</Link>}</div></section>{canManage && <section className="cc-panel sv-section"><h2>Assign an existing client</h2><p className="sv-muted">Records the agreed price and activates the configured project/task workflow. Connect an existing subscription ID to track billing; this form does not charge or email the client.</p><ActionForm action={assignClient} label="Assign & activate" confirm="Activate this client service and run its configured project/task workflow?"><input type="hidden" name="service_id" value={id} /><input type="hidden" name="activation_key" value={randomUUID()} /><div className="sv-fields"><label>Client<select className="cc-select" name="customer_id" required><option value="">Select client</option>{clients.data?.map(c => <option key={c.id} value={c.id}>{c.business_name || c.name || c.id}</option>)}</select></label><label>Agreed price per billing interval ($)<input name="sale_price" className="cc-input" type="number" min="0" step="0.01" defaultValue={s.from_cents/100} required /></label><label>Start Date<input name="start_date" type="date" className="cc-input" required /></label><label>Next Billing<input name="next_billing_date" type="date" className="cc-input" /></label><label>Existing subscription ID<input name="subscription_id" className="cc-input" /></label></div></ActionForm></section>}</>;
  } else if (tab === 'Sales') {
    const sales = await db.from('service_sales').select('*',{count:'exact'}).eq('service_id',id).order('occurred_at',{ascending:false}).range((page-1)*25,page*25-1);
    if (sales.error) throw new Error('Unable to load sales.');
    content = <><div className="sv-kpis">{Object.entries({'Total Sales':s.sales_count,'Total Revenue':money(s.revenue_cents),'MRR':money(s.mrr_cents),'Average Sale':s.sales_count ? money(s.revenue_cents/s.sales_count):'—','Active Clients':s.active_clients}).map(([label,value]) => <div key={label} className="sv-kpi"><span>{label}</span><strong>{value}</strong></div>)}</div><section className="cc-panel sv-section"><h2>Collected revenue</h2><p className="sv-muted">Attributed invoice receipts in USD. MRR is a run rate, not collected revenue. Unlinked historical transactions are excluded.</p><div className="ad-table-scroll"><table className="ad-table"><thead><tr>{['Date','Client','Proposal','Invoice','Amount','Status','Salesperson'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(sales.data as Sale[]).map((r,index)=><tr key={`${r.invoice_id}-${index}`}><td>{new Date(r.occurred_at).toLocaleDateString('en-US')}</td><td>{r.customer_id ? <Link className="cc-link" href={`/admin/clients/${r.customer_id}`}>{r.client_name || 'Client'}</Link> : r.client_name || '—'}</td><td>{r.proposal_id ? <Link className="cc-link" href={`/admin/proposals/${r.proposal_id}`}>View proposal</Link>:'—'}</td><td><Link className="cc-link" href={`/admin/invoices/${r.invoice_id}`}>{r.invoice_number}</Link></td><td>{money(r.amount_cents)}</td><td>{r.status}</td><td>{r.owner || '—'}</td></tr>)}</tbody></table></div>{!sales.data?.length && <p className="sv-muted">No collected revenue linked to this service yet.</p>}<div className="sv-pager"><span>{sales.count ?? 0} receipts</span>{page>1 && <Link href={`?tab=sales&page=${page-1}`}>Previous</Link>}{page*25<(sales.count??0) && <Link href={`?tab=sales&page=${page+1}`}>Next</Link>}</div><div className="sv-actions">{s.proposal_enabled && <Link className="cc-btn" href="/admin/proposals/new">Create proposal</Link>}{s.manual_invoice_enabled && <Link className="cc-btn" href="/admin/invoices/new">Create invoice</Link>}</div></section></>;
  } else {
    const [settings,templates,owners] = await Promise.all([db.from('service_automation_settings').select('*').eq('service_id',id).maybeSingle(),db.from('task_templates').select('id,name').eq('active',true).order('name'),db.from('admin_users').select('email,full_name')]);
    if (settings.error || templates.error || owners.error) throw new Error('Unable to load workflows.'); const a = settings.data as Automation | null;
    content = <section className="cc-panel sv-section"><h2>When a client service is activated</h2><p className="sv-muted">Uses the existing Projects and Tasks system. Replaying activation reuses the same project and task set.</p>{canManage ? <ActionForm action={saveAutomation}><input type="hidden" name="service_id" value={id} /><label className="sv-check"><input type="checkbox" name="create_project" defaultChecked={a?.create_project} />Create Project Automatically</label><div className="sv-fields"><label>Project / Task Template<select name="task_template_id" className="cc-select" defaultValue={a?.task_template_id ?? ''}><option value="">No task template</option>{templates.data?.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Default Assignee<select name="default_assignee" className="cc-select" defaultValue={a?.default_assignee ?? ''}><option value="">Unassigned</option>{owners.data?.map(o=><option key={o.email} value={o.email}>{o.full_name || o.email}</option>)}</select></label><label>Project due-date offset (days)<input type="number" name="due_date_offset_days" className="cc-input" min={0} max={3650} defaultValue={a?.due_date_offset_days ?? 14} required /></label></div><label className="sv-check"><input type="checkbox" name="notify_admin" defaultChecked={a?.notify_admin} />Create an admin review task on activation</label></ActionForm> : <p className="sv-muted">Only owners and admins can change automation settings.</p>}<p className="sv-muted">Welcome emails, intake delivery, payment-provider subscriptions, and website/hosting provisioning continue through their existing workflows. No external messages or provisioning are triggered by this setting.</p></section>;
  }
  return <><div className="cc-greet"><div><Link className="cc-link" href="/admin/services">← Services</Link><h1>{s.name}</h1><p><span className={`sv-badge sv-${s.status}`}>{s.status}</span> · {s.service_type} · {s.category.replaceAll('_',' ')} · {priceLabel(s)}</p></div><div className="sv-actions"><Link className="cc-btn" href="/admin/catalog">View Catalog</Link>{canManage && <ServiceModal service={s} />}</div></div><nav className="sv-tabs" aria-label="Service sections">{TABS.map(t=><Link key={t} href={`?tab=${t.toLowerCase()}`} aria-current={tab===t ? 'page':undefined}>{t}</Link>)}</nav>{content}</>;
}
