import Link from 'next/link';
/* eslint-disable @next/next/no-img-element -- authenticated primary media uses a protected route */
import { notFound, redirect } from 'next/navigation';
import { randomUUID } from 'node:crypto';
import { createSupabaseServerClient, getAdminUser } from '@/lib/supabase/server';
import { loadClientServices } from '@/lib/services/queries';
import { isUuid, money, marginLabel, priceLabel } from '@/lib/services/pricing';
import { BILLING_LABELS, SERVICE_HEALTH_LABELS, type Automation, type Service, type ServiceDeliverable, type ServiceInclusion, type Sale } from '@/lib/services/types';
import { ActionForm, ServiceEditor, ServiceModal, StatusAction } from '@/components/admin/cc/services/ServiceForms';
import { CostsPanel, PricingTermsPanel, StructuredItemsPanel } from '@/components/admin/cc/services/ServiceOperations';
import ClientAssignments from '@/components/admin/cc/services/ClientAssignments';
import ServiceAdCreative from '@/components/admin/cc/services/ServiceAdCreative';
import { assignClient, savePackage, removePackage, saveAutomation } from '@/app/admin/service-actions';

export const dynamic = 'force-dynamic';
const TABS = ['Overview', "What's Included", 'Creative', 'Clients', 'Pricing', 'Costs', 'Deliverables', 'Automations', 'Performance', 'Billing', 'Packages', 'Settings'] as const;
const tabSlug = (tab: string) => tab.toLowerCase().replaceAll("'", '').replaceAll(' ', '-');

function Metrics({ service, canManage }: { service: Service; canManage: boolean }) {
  const average = service.active_clients > 0 ? (service.billing_type === 'recurring' ? service.mrr_cents : service.revenue_cents) / service.active_clients : null;
  const metrics: [string, string | number, string][] = [
    ['Active Clients', service.active_clients, 'Current assignments'],
    [service.billing_type === 'recurring' ? 'Monthly Recurring Revenue' : 'Collected Revenue', money(service.billing_type === 'recurring' ? service.mrr_cents : service.revenue_cents), service.billing_type === 'recurring' ? 'Current monthly run rate' : 'All linked receipts'],
    ...(canManage ? [
      ['Internal Cost', service.effective_cost_cents == null ? 'Cost not set' : money(service.calculated_internal_cost_cents ?? service.effective_cost_cents), service.billing_type === 'recurring' ? 'Current monthly total' : 'Estimated per sale'],
      ['Gross Profit', service.gross_profit_cents == null ? '—' : money(service.gross_profit_cents), 'Based only on configured costs'],
      ['Gross Margin', marginLabel(service.margin), `Target ${Number(service.margin_threshold_pct).toFixed(0)}%`],
    ] as [string,string,string][] : []),
    ['Average Client Value', average == null ? '—' : money(average), service.billing_type === 'recurring' ? 'Monthly' : 'Recorded revenue'],
  ];
  return <div className="sv-kpis sv-detail-kpis">{metrics.map(([label,value,note]) => <section className="sv-kpi" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></section>)}</div>;
}

function SalesTable({ sales }: { sales: Sale[] }) {
  if (!sales.length) return <p className="sv-muted">No collected revenue linked to this service yet.</p>;
  return <div className="ad-table-scroll"><table className="ad-table"><thead><tr>{['Date','Client','Invoice','Amount','Status','Salesperson'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{sales.map((row,index)=><tr key={`${row.invoice_id}-${index}`}><td>{new Date(row.occurred_at).toLocaleDateString('en-US')}</td><td>{row.customer_id ? <Link className="cc-link" href={`/admin/clients/${row.customer_id}`}>{row.client_name || 'Client'}</Link> : row.client_name || '—'}</td><td><Link className="cc-link" href={`/admin/invoices/${row.invoice_id}`}>{row.invoice_number}</Link></td><td>{money(row.amount_cents)}</td><td>{row.status}</td><td>{row.owner || '—'}</td></tr>)}</tbody></table></div>;
}

export default async function ServiceDetail({ params, searchParams }: { params: Promise<{id:string}>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const session = await getAdminUser(); if (!session) redirect('/admin/login');
  const { id } = await params; if (!isUuid(id)) notFound();
  const canManage = ['owner','admin'].includes(session.admin.role); const db = await createSupabaseServerClient();
  const [{ data, error }, { data: creative, error: creativeError }] = await Promise.all([
    db.from('service_directory').select('*').eq('id',id).maybeSingle(),
    db.from('catalog_items').select('ad_image_path,image_path,image_url,image_alt').eq('id',id).maybeSingle(),
  ]);
  if (error || creativeError) throw new Error('Unable to load service.'); if (!data || !creative) notFound(); const service = data as Service;
  const query = await searchParams; const requestedTab = typeof query.tab === 'string' ? query.tab : 'overview';
  const tab = TABS.find(candidate => tabSlug(candidate) === requestedTab) ?? 'Overview';
  const page = Math.max(1,Math.min(100000,parseInt(typeof query.page === 'string' ? query.page : '1') || 1));
  let content: React.ReactNode;

  if (tab === 'Overview') {
    const [events, inclusions] = await Promise.all([
      db.from('service_events').select('id,body,actor,created_at').eq('service_id',id).order('created_at',{ascending:false}).limit(8),
      db.from('service_inclusions').select('*').eq('service_id',id).order('sort_order').order('created_at').limit(5),
    ]);
    if (events.error || inclusions.error) throw new Error('Unable to load service overview.');
    content = <div className="sv-detail-grid"><section className="cc-panel sv-section"><h2>Service description</h2><p className="sv-description">{service.description || 'No description yet.'}</p><dl className="sv-definition"><div><dt>Billing</dt><dd>{BILLING_LABELS[service.billing_type]}</dd></div><div><dt>Standard Price</dt><dd>{priceLabel(service)}</dd></div><div><dt>Status</dt><dd>{service.status}</dd></div><div><dt>Total Sales</dt><dd>{service.sales_count}</dd></div><div><dt>Created</dt><dd>{new Date(service.created_at).toLocaleDateString('en-US')}</dd></div><div><dt>Last Updated</dt><dd>{new Date(service.updated_at).toLocaleDateString('en-US')}</dd></div></dl></section><section className="cc-panel sv-section"><div className="sv-section-heading"><div><h2>What’s included</h2><p className="sv-muted">Customer-facing promise preview</p></div><Link className="cc-link" href="?tab=whats-included">View All Inclusions</Link></div>{inclusions.data?.length ? <ul className="sv-preview-list">{(inclusions.data as ServiceInclusion[]).map(item=><li key={item.id}><span>{item.is_optional_addon ? '+' : '✓'}</span><div><strong>{item.name}</strong><small>{item.client_facing_description || item.description || 'Details not added yet.'}</small></div></li>)}</ul> : <p className="sv-muted">No structured inclusions yet.</p>}</section><section className="cc-panel sv-section sv-span-all"><h2>Recent activity</h2>{events.data?.length ? <div className="sv-activity">{events.data.map(event => <div key={event.id}><span>{event.body}</span><small>{event.actor} · {new Date(event.created_at).toLocaleString('en-US')}</small></div>)}</div> : <p className="sv-muted">No activity recorded yet.</p>}</section></div>;
  } else if (tab === "What's Included") {
    const { data:items,error:itemsError } = await db.from('service_inclusions').select('*').eq('service_id',id).order('sort_order').order('created_at'); if (itemsError) throw new Error('Unable to load inclusions.');
    content = <StructuredItemsPanel serviceId={id} items={(items ?? []) as ServiceInclusion[]} canManage={canManage} />;
  } else if (tab === 'Creative') {
    content = <section className="cc-panel sv-section"><div className="sv-section-heading"><div><h2>Media / Ads</h2><p className="sv-muted">Generate full campaign-ready creative sets or keep one manually uploaded service image.</p></div>{canManage&&<Link className="cc-btn primary" href={`/admin/marketing/ads?catalog=${id}`}>Generate New Ad</Link>}</div>{(creative.image_path||creative.image_url)&&<div className="sv-primary-creative"><span className="sv-eyebrow">Primary image</span><img src={creative.image_path?`/api/admin/catalog-media/${id}`:creative.image_url!} alt={creative.image_alt||`${service.name} primary image`}/></div>}<ServiceAdCreative serviceId={id} serviceName={service.name} imagePath={creative.ad_image_path} version={service.updated_at} canManage={canManage} /></section>;
  } else if (tab === 'Clients') {
    const [assignments, clients, owners] = await Promise.all([loadClientServices(db,{serviceId:id},page), canManage ? db.from('customers').select('id,name,business_name').order('business_name').limit(1000) : Promise.resolve({data:[],error:null}), canManage ? db.from('admin_users').select('email,full_name').order('full_name') : Promise.resolve({data:[],error:null})]);
    if (clients.error || owners.error) throw new Error('Unable to load clients.');
    content = <><section className="cc-panel sv-section"><h2>Clients using this service</h2><ClientAssignments rows={assignments.rows} canManage={canManage} /><div className="sv-pager"><span>{assignments.count} assignments</span>{page>1 && <Link href={`?tab=clients&page=${page-1}`}>Previous</Link>}{page*25<assignments.count && <Link href={`?tab=clients&page=${page+1}`}>Next</Link>}</div></section>{canManage && <section className="cc-panel sv-section"><h2>Assign an existing client</h2><p className="sv-muted">Records the agreed price and activates the configured project/task workflow. It does not charge or email the client.</p><ActionForm action={assignClient} label="Assign & Activate" confirm="Activate this client service and run its configured project/task workflow?"><input type="hidden" name="service_id" value={id} /><input type="hidden" name="activation_key" value={randomUUID()} /><div className="sv-fields"><label>Client<select className="cc-select" name="customer_id" required><option value="">Select client</option>{clients.data?.map(client => <option key={client.id} value={client.id}>{client.business_name || client.name || client.id}</option>)}</select></label><label>Agreed Price ($)<input name="sale_price" className="cc-input" type="number" min="0" step="0.01" defaultValue={service.from_cents/100} required /></label><label>Start Date<input name="start_date" type="date" className="cc-input" required /></label><label>Next Billing<input name="next_billing_date" type="date" className="cc-input" /></label><label>Assigned Manager<select className="cc-select" name="assigned_manager"><option value="">Unassigned</option>{owners.data?.map(owner=><option key={owner.email} value={owner.email}>{owner.full_name || owner.email}</option>)}</select></label><label>Billing Status<select className="cc-select" name="billing_status" defaultValue="not_connected"><option value="not_connected">Not Connected</option><option value="active">Active</option><option value="past_due">Past Due</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option></select></label><label>Existing Subscription ID<input name="subscription_id" className="cc-input" /></label></div></ActionForm></section>}</>;
  } else if (tab === 'Pricing') {
    const history = await db.from('service_price_history').select('*').eq('service_id',id).order('created_at',{ascending:false}).limit(25); if (history.error) throw new Error('Unable to load pricing.');
    content = <><section className="cc-panel sv-section"><h2>Standard price and billing model</h2>{canManage ? <ServiceEditor service={service} /> : <dl className="sv-definition"><div><dt>Standard Price</dt><dd>{priceLabel(service)}</dd></div><div><dt>Billing Type</dt><dd>{BILLING_LABELS[service.billing_type]}</dd></div></dl>}</section><PricingTermsPanel service={service} canManage={canManage} /><section className="cc-panel sv-section"><h2>Price history</h2>{history.data?.length ? <div className="sv-activity">{history.data.map(row => <div key={row.id}><span>{money(row.price_cents)} · {BILLING_LABELS[row.billing_type]} · Setup {money(row.setup_fee_cents)}</span><small>{new Date(row.created_at).toLocaleString('en-US')} · {row.actor}</small></div>)}</div> : <p className="sv-muted">Future price changes will be recorded here.</p>}</section></>;
  } else if (tab === 'Costs') {
    content = canManage ? <CostsPanel service={service} canManage /> : <section className="cc-panel sv-section"><p className="sv-muted">Detailed costs are restricted to owners and administrators.</p></section>;
  } else if (tab === 'Deliverables') {
    const { data:items,error:itemsError } = await db.from('service_deliverables').select('*').eq('service_id',id).order('sort_order').order('created_at'); if (itemsError) throw new Error('Unable to load deliverables.');
    content = <StructuredItemsPanel serviceId={id} items={(items ?? []) as ServiceDeliverable[]} deliverable canManage={canManage} />;
  } else if (tab === 'Automations') {
    const [settings,templates,owners] = await Promise.all([db.from('service_automation_settings').select('*').eq('service_id',id).maybeSingle(),db.from('task_templates').select('id,name').eq('active',true).order('name'),db.from('admin_users').select('email,full_name')]); if (settings.error || templates.error || owners.error) throw new Error('Unable to load workflows.'); const automation = settings.data as Automation | null;
    content = <section className="cc-panel sv-section"><h2>When a client service is activated</h2><p className="sv-muted">Uses the existing Projects and Tasks system. Delivery templates are ready for future automation without triggering external actions today.</p>{canManage ? <ActionForm action={saveAutomation}><input type="hidden" name="service_id" value={id} /><label className="sv-check"><input type="checkbox" name="create_project" defaultChecked={automation?.create_project} />Create Project Automatically</label><div className="sv-fields"><label>Project / Task Template<select name="task_template_id" className="cc-select" defaultValue={automation?.task_template_id ?? ''}><option value="">No task template</option>{templates.data?.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select></label><label>Default Assignee<select name="default_assignee" className="cc-select" defaultValue={automation?.default_assignee ?? ''}><option value="">Unassigned</option>{owners.data?.map(owner=><option key={owner.email} value={owner.email}>{owner.full_name || owner.email}</option>)}</select></label><label>Project Due Offset (days)<input type="number" name="due_date_offset_days" className="cc-input" min={0} max={3650} defaultValue={automation?.due_date_offset_days ?? 14} required /></label></div><label className="sv-check"><input type="checkbox" name="notify_admin" defaultChecked={automation?.notify_admin} />Create an admin review task on activation</label></ActionForm> : <p className="sv-muted">Only owners and admins can change automation settings.</p>}</section>;
  } else if (tab === 'Performance') {
    const sales = await db.from('service_sales').select('*').eq('service_id',id).order('occurred_at',{ascending:false}).limit(25); if (sales.error) throw new Error('Unable to load performance.');
    content = <><section className="cc-panel sv-section"><div className="sv-section-heading"><div><h2>Service health</h2><p className="sv-muted">Derived from configured costs, active clients, billing setup, and the margin target.</p></div>{canManage && <span className={`sv-badge sv-health-${service.health}`}>{SERVICE_HEALTH_LABELS[service.health]}</span>}</div>{canManage && service.health==='missing_cost' && <p className="sv-callout">Add costs before using profitability figures for pricing decisions.</p>}{service.health==='no_clients' && <p className="sv-callout">This active service has no current client assignments.</p>}</section><section className="cc-panel sv-section"><h2>Collected revenue</h2><SalesTable sales={(sales.data ?? []) as Sale[]} /></section></>;
  } else if (tab === 'Billing') {
    const assignments = await loadClientServices(db,{serviceId:id},page);
    content = <section className="cc-panel sv-section"><h2>Billing relationships</h2><p className="sv-muted">Assignment status, billing state, recurring amount, and next billing date. Changes here do not charge the payment provider.</p><ClientAssignments rows={assignments.rows} canManage={canManage} /></section>;
  } else if (tab === 'Packages') {
    const [links, options] = await Promise.all([db.from('service_package_relationships').select('*,package:catalog_items!package_id(name)').eq('service_id',id),db.from('catalog_items').select('id,name').eq('offer_kind','package').neq('status','retired').order('name').limit(1000)]); if (links.error || options.error) throw new Error('Unable to load packages.');
    content = <><section className="cc-panel sv-section"><h2>Package relationships</h2>{['included','addon'].map(kind => <div key={kind}><h3>{kind==='included' ? 'Included In Packages':'Optional Add-On For Packages'}</h3>{links.data?.filter(row=>row.relationship_type===kind).length ? links.data.filter(row=>row.relationship_type===kind).map(row => <div key={row.id} className="sv-pager"><div><Link className="cc-link" href={`/admin/services/${row.package_id}`}>{row.package?.name}</Link> · Quantity {row.quantity}<p className="sv-muted">{row.notes}</p></div>{canManage && <ActionForm action={removePackage} label="Remove" confirm="Remove this package relationship?"><input type="hidden" name="id" value={row.id} /><input type="hidden" name="service_id" value={id} /></ActionForm>}</div>) : <p className="sv-muted">No relationships yet.</p>}</div>)}</section>{canManage && <section className="cc-panel sv-section"><h2>Add or update relationship</h2><ActionForm action={savePackage}><input type="hidden" name="service_id" value={id} /><div className="sv-fields"><label>Package<select name="package_id" required className="cc-select"><option value="">Select an existing Catalog package</option>{options.data?.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>Relationship<select name="relationship_type" className="cc-select"><option value="included">Included</option><option value="addon">Optional add-on</option></select></label><label>Quantity / Limit<input type="number" name="quantity" className="cc-input" min="0.01" step="0.01" defaultValue="1" required /></label><label>Notes<input name="notes" className="cc-input" /></label></div></ActionForm></section>}</>;
  } else {
    content = <section className="cc-panel sv-section"><h2>Service status and availability</h2>{canManage ? <><ServiceEditor service={service} /><div className="sv-actions"><StatusAction service={service} status={service.status==='active' ? 'paused':'active'} />{service.status!=='retired' && <StatusAction service={service} status="retired" />}</div></> : <p className="sv-muted">Only owners and admins can change service settings.</p>}</section>;
  }

  return <><div className="cc-greet"><div><Link className="cc-link" href="/admin/services">← Services</Link><h1>{service.name}</h1><p><span className={`sv-badge sv-${service.status}`}>{service.status}</span> · {service.service_type} · {service.category.replaceAll('_',' ')} · {priceLabel(service)}</p></div><div className="sv-actions"><Link className="cc-btn" href="/admin/catalog">View Catalog</Link>{canManage && <ServiceModal service={service} />}</div></div><Metrics service={service} canManage={canManage} /><nav className="sv-tabs" aria-label="Service sections">{TABS.map(candidate=><Link key={candidate} href={`?tab=${tabSlug(candidate)}`} aria-current={tab===candidate ? 'page':undefined}>{candidate}</Link>)}</nav>{content}</>;
}
