"use client";

import { renderLogoSvg } from "@/lib/logo-studio/render";
import type { Brief, Concept, Palette } from "@/lib/logo-studio/types";

/**
 * "See your brand alive."
 *
 * Coded scenes rather than photography: they cost no image payload, update the
 * instant a colour or font changes, and carry no licensing questions. Each
 * scene is a CSS/SVG stage with the live logo composited in, so what a customer
 * sees here is the same markup that lands in their download.
 */

type Props = { concept: Concept; brief: Brief; palette: Palette };

function Logo({
  concept,
  brief,
  palette,
  ns,
  onLight = false,
  layout,
  className,
}: Props & { ns: string; onLight?: boolean; layout?: "stacked" | "horizontal" | "iconOnly"; className?: string }) {
  const svg = renderLogoSvg(concept, brief, { palette, onLight, layout, ns });
  return (
    <span
      className={className}
      // Markup is generated by our own renderer and every user-supplied string
      // passes through escapeXml first, so there is no injection surface here.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}

export function Mockups(props: Props) {
  const { palette } = props;

  return (
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
      {/* ── Storefront sign ─────────────────────────────────────────── */}
      <Scene label="Storefront">
        <div className="absolute inset-0 bg-gradient-to-b from-[#141a24] via-[#0d1219] to-[#070a10]" />
        {/* building face */}
        <div className="absolute inset-x-0 top-0 h-[58%] bg-[#1a212c] border-b border-black/50" />
        {/* windows */}
        <div className="absolute inset-x-[8%] bottom-[6%] h-[30%] grid grid-cols-3 gap-1.5">
          {[0, 1, 2].map((i) => (
            <div key={i} className="rounded-sm bg-gradient-to-b from-[#2a3646] to-[#161d27]" />
          ))}
        </div>
        {/* lit sign */}
        <div className="absolute inset-x-[14%] top-[14%]">
          <Logo {...props} ns="mk-store" layout="horizontal" className="mk-svg block drop-shadow-[0_0_18px_rgba(120,180,255,.45)]" />
        </div>
        <div
          className="absolute inset-x-[10%] top-[13%] h-[26%] blur-2xl opacity-40 rounded-full"
          style={{ background: palette.primary }}
        />
      </Scene>

      {/* ── Vehicle wrap ────────────────────────────────────────────── */}
      <Scene label="Vehicle">
        <div className="absolute inset-0 bg-gradient-to-b from-[#101620] to-[#05080d]" />
        <svg viewBox="0 0 300 150" className="absolute inset-0 w-full h-full" aria-hidden="true">
          {/* van silhouette */}
          <path d="M26 104V60l30-26h84v70z" fill="#E7ECF2" />
          <path d="M140 104V34h70l38 34v36z" fill="#DDE3EB" />
          <path d="M150 44h48l26 24h-74z" fill="#7B8794" opacity=".55" />
          <path d="M64 42h64v22H46z" fill="#7B8794" opacity=".5" />
          <rect x="20" y="100" width="240" height="8" rx="4" fill="#0C1017" />
          <circle cx="74" cy="110" r="14" fill="#11161F" />
          <circle cx="74" cy="110" r="6" fill="#333C49" />
          <circle cx="214" cy="110" r="14" fill="#11161F" />
          <circle cx="214" cy="110" r="6" fill="#333C49" />
        </svg>
        <div className="absolute left-[12%] top-[46%] w-[38%]">
          <Logo {...props} ns="mk-van" layout="horizontal" onLight className="mk-svg block" />
        </div>
      </Scene>

      {/* ── Business card ───────────────────────────────────────────── */}
      <Scene label="Business card">
        <div className="absolute inset-0 bg-gradient-to-br from-[#161c26] to-[#080b11]" />
        <div
          className="absolute left-[10%] top-[16%] w-[62%] aspect-[1.75/1] rounded-md shadow-2xl rotate-[-6deg] flex items-center justify-center p-4"
          style={{ background: palette.deep, boxShadow: "0 18px 40px rgba(0,0,0,.6)" }}
        >
          <Logo {...props} ns="mk-card" className="mk-svg block max-h-full" />
        </div>
        <div className="absolute right-[8%] bottom-[12%] w-[52%] aspect-[1.75/1] rounded-md bg-white shadow-2xl rotate-[4deg] p-3 flex flex-col justify-between">
          <Logo {...props} ns="mk-card2" layout="horizontal" onLight className="mk-svg block w-[74%]" />
          <div className="space-y-[3px]">
            <div className="h-[3px] w-[52%] rounded-full bg-slate-300" />
            <div className="h-[3px] w-[38%] rounded-full bg-slate-200" />
          </div>
        </div>
      </Scene>

      {/* ── Phone app ───────────────────────────────────────────────── */}
      <Scene label="App icon">
        <div className="absolute inset-0 bg-gradient-to-b from-[#131924] to-[#06090e]" />
        <div className="absolute left-1/2 -translate-x-1/2 top-[10%] w-[42%] aspect-[9/17] rounded-[14px] border-[3px] border-[#2a3340] bg-[#0a0e15] overflow-hidden shadow-2xl">
          <div className="h-3 flex items-center justify-center">
            <div className="w-8 h-1 rounded-full bg-[#2a3340]" />
          </div>
          <div className="grid grid-cols-3 gap-1.5 p-2">
            <div
              className="col-span-1 aspect-square rounded-[9px] flex items-center justify-center p-1"
              style={{ background: palette.deep, outline: `1.5px solid ${palette.primary}66` }}
            >
              <Logo {...props} ns="mk-app" layout="iconOnly" className="mk-svg block w-full" />
            </div>
            {Array.from({ length: 5 }).map((_, i) => (
              <div key={i} className="aspect-square rounded-[9px] bg-white/[0.05]" />
            ))}
          </div>
        </div>
      </Scene>

      {/* ── Shirt ───────────────────────────────────────────────────── */}
      <Scene label="Uniform">
        <div className="absolute inset-0 bg-gradient-to-b from-[#151b25] to-[#070a10]" />
        <svg viewBox="0 0 200 150" className="absolute inset-0 w-full h-full" aria-hidden="true">
          <path
            d="M70 24 55 32 30 46l12 24 14-7v55h88V63l14 7 12-24-25-14-15-8-15 10h-18z"
            fill={palette.deep}
            stroke="rgba(255,255,255,.09)"
          />
          <path d="M85 24h30l-15 12z" fill="rgba(0,0,0,.4)" />
        </svg>
        <div className="absolute left-1/2 -translate-x-1/2 top-[46%] w-[34%]">
          <Logo {...props} ns="mk-shirt" className="mk-svg block" />
        </div>
      </Scene>

      {/* ── Website hero ────────────────────────────────────────────── */}
      <Scene label="Website">
        <div className="absolute inset-0 bg-[#0a0e15]" />
        <div className="absolute inset-x-[6%] top-[10%] bottom-[10%] rounded-md border border-white/10 overflow-hidden" style={{ background: palette.deep }}>
          <div className="h-5 border-b border-white/10 flex items-center gap-1 px-2">
            {["#ef4444", "#eab308", "#22c55e"].map((c) => (
              <span key={c} className="w-1.5 h-1.5 rounded-full" style={{ background: c }} />
            ))}
          </div>
          <div className="flex items-center justify-between px-2.5 py-2 border-b border-white/[0.07]">
            <Logo {...props} ns="mk-web" layout="horizontal" className="mk-svg block w-[38%]" />
            <div className="flex gap-1.5">
              {[0, 1, 2].map((i) => (
                <span key={i} className="h-1 w-5 rounded-full bg-white/15" />
              ))}
            </div>
          </div>
          <div className="p-3 space-y-1.5">
            <div className="h-2 w-[70%] rounded-full" style={{ background: palette.primary }} />
            <div className="h-1.5 w-[88%] rounded-full bg-white/12" />
            <div className="h-1.5 w-[62%] rounded-full bg-white/10" />
            <div className="h-4 w-[34%] rounded mt-2" style={{ background: palette.primary }} />
          </div>
        </div>
      </Scene>
    </div>
  );
}

function Scene({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <figure className="relative rounded-xl border border-[color:var(--color-border)] overflow-hidden aspect-[4/3] bg-[color:var(--color-surface)]">
      {children}
      <figcaption className="absolute left-2.5 bottom-2 text-[9.5px] font-semibold tracking-[0.16em] uppercase text-white/45 z-10">
        {label}
      </figcaption>
    </figure>
  );
}
