import { renderLogoSvg } from "./render";
import { makeZip } from "./zip";
import type { Brief, Concept, Palette } from "./types";

/**
 * Brand kit assembly. Runs entirely in the browser — no upload, no server
 * round-trip, and nothing about the customer's business leaves their machine
 * until they choose to give you an email.
 */

/** Rasterise an SVG string at a given pixel width. */
export async function svgToPng(svg: string, width: number, background?: string): Promise<Uint8Array> {
  const img = new Image();
  // base64 rather than encodeURIComponent so non-ASCII business names survive.
  const b64 = btoa(unescape(encodeURIComponent(svg)));
  img.src = `data:image/svg+xml;base64,${b64}`;
  await img.decode();

  const ratio = img.naturalHeight / img.naturalWidth || 1;
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = Math.round(width * ratio);
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas unavailable");
  if (background) {
    ctx.fillStyle = background;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
  }
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

  const blob = await new Promise<Blob | null>((res) => canvas.toBlob(res, "image/png"));
  if (!blob) throw new Error("PNG encode failed");
  return new Uint8Array(await blob.arrayBuffer());
}

/** Square icon on an opaque tile — for favicons and app/social avatars. */
async function iconPng(concept: Concept, brief: Brief, size: number, palette: Palette) {
  const mark = renderLogoSvg(concept, brief, { layout: "iconOnly", palette, ns: "icon" });
  const padded = mark.replace(
    /viewBox="0 0 200 200"/,
    'viewBox="-30 -30 260 260"'
  );
  return svgToPng(padded, size, palette.deep);
}

function slug(s: string) {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "logo"
  );
}

export async function buildBrandKit(concept: Concept, brief: Brief, palette: Palette) {
  const base = slug(brief.businessName);
  const onDark = { palette, onLight: false as const };
  const onLight = { palette, onLight: true as const };

  const primarySvg = renderLogoSvg(concept, brief, { ...onDark, standalone: true, ns: "primary" });
  const lightSvg = renderLogoSvg(concept, brief, { ...onLight, standalone: true, ns: "light" });
  const iconSvg = renderLogoSvg(concept, brief, { ...onDark, layout: "iconOnly", standalone: true, ns: "icononly" });
  const horizSvg = renderLogoSvg(concept, brief, { ...onDark, layout: "horizontal", standalone: true, ns: "horiz" });

  const rasterSource = renderLogoSvg(concept, brief, { ...onDark, ns: "raster" });
  const rasterLight = renderLogoSvg(concept, brief, { ...onLight, ns: "rasterlight" });

  const files: { name: string; data: Uint8Array | string }[] = [
    { name: `${base}/vector/${base}-primary.svg`, data: primarySvg },
    { name: `${base}/vector/${base}-on-light.svg`, data: lightSvg },
    { name: `${base}/vector/${base}-horizontal.svg`, data: horizSvg },
    { name: `${base}/vector/${base}-icon.svg`, data: iconSvg },
    { name: `${base}/png/${base}-2048.png`, data: await svgToPng(rasterSource, 2048) },
    { name: `${base}/png/${base}-1024.png`, data: await svgToPng(rasterSource, 1024) },
    { name: `${base}/png/${base}-512.png`, data: await svgToPng(rasterSource, 512) },
    { name: `${base}/png/${base}-on-light-1024.png`, data: await svgToPng(rasterLight, 1024, "#FFFFFF") },
    { name: `${base}/icons/icon-512.png`, data: await iconPng(concept, brief, 512, palette) },
    { name: `${base}/icons/icon-192.png`, data: await iconPng(concept, brief, 192, palette) },
    { name: `${base}/icons/favicon-48.png`, data: await iconPng(concept, brief, 48, palette) },
    { name: `${base}/brand-guide.html`, data: brandGuide(concept, brief, palette) },
    { name: `${base}/colors.txt`, data: colorsTxt(palette) },
    { name: `${base}/README.txt`, data: readme(brief, concept, palette) },
  ];

  return { blob: makeZip(files), filename: `${base}-brand-kit.zip` };
}

function colorsTxt(p: Palette) {
  return [
    `Brand colours — ${p.name}`,
    ``,
    `Primary    ${p.primary}`,
    `Secondary  ${p.secondary}`,
    `Deep       ${p.deep}`,
    `Light      ${p.light}`,
    ``,
    `Use Primary for the mark and key actions. Secondary is for highlights and`,
    `gradients. Deep is your dark background. Light is text on dark.`,
    ``,
  ].join("\n");
}

function readme(brief: Brief, concept: Concept, p: Palette) {
  return [
    `${brief.businessName} — brand kit`,
    `Generated by Tomorrow's Tech AI Logo Studio`,
    ``,
    `WHAT'S IN HERE`,
    `  vector/   Scalable SVG. Use these for signs, vehicle wraps and print.`,
    `  png/      Ready-to-use images for web, social and documents.`,
    `  icons/    Square icons for favicons, app icons and social avatars.`,
    ``,
    `TYPEFACE`,
    `  ${concept.font.name}`,
    `  The SVG files reference this by name. If it isn't installed on the`,
    `  machine opening them, the next font in the stack is used instead. Install`,
    `  the typeface for an exact match, or ask us to outline the text for you.`,
    ``,
    `COLOURS`,
    `  Primary ${p.primary} · Secondary ${p.secondary} · Deep ${p.deep}`,
    ``,
    `WANT THIS REFINED?`,
    `  This kit was generated from your brief. Our designers can hand-refine the`,
    `  mark, build the full colour and type system, and extend it across your`,
    `  website, stationery and vehicles.`,
    `  tomorrowstechai.com/logo-studio`,
    ``,
  ].join("\n");
}

function brandGuide(concept: Concept, brief: Brief, p: Palette) {
  const dark = renderLogoSvg(concept, brief, { palette: p, onLight: false, ns: "gd" });
  const light = renderLogoSvg(concept, brief, { palette: p, onLight: true, ns: "gl" });
  const swatch = (label: string, hex: string) =>
    `<div class="sw"><div class="chip" style="background:${hex}"></div><b>${label}</b><code>${hex}</code></div>`;

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>${brief.businessName} — brand guide</title>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<style>
  :root{color-scheme:dark}
  body{margin:0;background:${p.deep};color:${p.light};font:16px/1.6 ${concept.font.stack};padding:48px 32px}
  .wrap{max-width:880px;margin:0 auto}
  h1{font-size:14px;letter-spacing:.24em;text-transform:uppercase;color:${p.primary};margin:0 0 8px}
  h2{font-size:12px;letter-spacing:.2em;text-transform:uppercase;opacity:.6;margin:48px 0 16px;font-weight:600}
  .panel{border:1px solid rgba(255,255,255,.12);border-radius:14px;padding:40px;display:flex;
         align-items:center;justify-content:center;min-height:200px}
  .panel.light{background:#fff}
  .panel svg{max-width:100%;height:auto}
  .row{display:grid;grid-template-columns:1fr 1fr;gap:16px}
  .sw{border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:14px}
  .chip{height:56px;border-radius:8px;margin-bottom:10px}
  .sw b{display:block;font-size:13px}
  .sw code{font-size:12px;opacity:.65}
  .grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}
  footer{margin-top:56px;padding-top:20px;border-top:1px solid rgba(255,255,255,.12);font-size:12px;opacity:.55}
  @media(max-width:640px){.row,.grid4{grid-template-columns:1fr}}
</style></head>
<body><div class="wrap">
  <h1>Brand guide</h1>
  <div style="font-size:30px;font-weight:800;letter-spacing:-.02em">${brief.businessName}</div>

  <h2>Primary lockup</h2>
  <div class="panel">${dark}</div>

  <h2>On light backgrounds</h2>
  <div class="panel light">${light}</div>

  <h2>Colour</h2>
  <div class="grid4">
    ${swatch("Primary", p.primary)}${swatch("Secondary", p.secondary)}
    ${swatch("Deep", p.deep)}${swatch("Light", p.light)}
  </div>

  <h2>Typeface</h2>
  <div class="row">
    <div class="sw"><b style="font-size:26px">${concept.font.name}</b><code>Business name — weight ${concept.font.nameWeight}</code></div>
    <div class="sw"><b style="font-size:26px;font-weight:${concept.font.subWeight}">${concept.font.name}</b><code>Supporting text — weight ${concept.font.subWeight}</code></div>
  </div>

  <h2>Clear space &amp; minimum size</h2>
  <p style="opacity:.75;font-size:14px">Leave clear space around the lockup equal to the height of the mark's
  shortest side. Do not reproduce the full lockup below 120px wide — use the icon-only version instead.</p>

  <footer>Generated by Tomorrow&rsquo;s Tech AI Logo Studio · tomorrowstechai.com</footer>
</div></body></html>`;
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick so Safari has time to start the download.
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
