"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { BrandDetail } from "@/lib/brand/queries";
import { addColorAction, addTypographyAction, archiveBrandAction, saveBrandKitAction, saveGuidelineAction, saveMessagingAction, saveTemplateAction } from "@/app/admin/brand-actions";
import { IconCheck, IconFile, IconPlus, IconX } from "../Icons";
import styles from "./BrandAssets.module.css";
import detail from "./BrandDetail.module.css";

const ROOT = "/admin/marketing/brand";
const TABS = ["overview","logos","colors","typography","media","templates","messaging","guidelines","usage","activity","settings"];
const label = (v: string) => v.replace(/_/g," ").replace(/\b\w/g,(c) => c.toUpperCase());
const listText = (v: string[]) => v.join(", ");

function Section({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className={detail.section}><header><h2>{title}</h2>{action}</header>{children}</section>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className={detail.empty}><IconFile size={24}/><b>{title}</b><p>{text}</p></div>; }

function UploadModal({ b, close }: { b: BrandDetail; close: () => void }) {
  const router = useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const res=await fetch("/api/admin/assets",{method:"POST",body:fd});const body=await res.json().catch(()=>({}));setBusy(false);if(!res.ok){setError(body.error||"Upload failed.");return;}close();router.refresh();}
  return <div className={styles.scrim} onMouseDown={e=>e.target===e.currentTarget&&close()}><section className={styles.modal}><header><div><h2>Upload Asset</h2><p>Stored privately and attached to {b.name}.</p></div><button onClick={close}><IconX/></button></header><form className={styles.form} onSubmit={upload}><input type="hidden" name="brand_profile_id" value={b.id}/><label>File<input type="file" name="file" accept="image/*,video/*,audio/*,application/pdf" required/></label><label>Asset Type<select name="asset_type"><option value="logo">Logo</option><option value="brand_graphic">Brand Graphic</option><option value="photo">Photo</option><option value="video">Video</option><option value="template">Template</option><option value="document">Document</option></select></label><label>Role<input name="role" placeholder="Primary, horizontal, email header…"/></label><p className={detail.note}>New uploads enter the approval queue and cannot be used in client-facing systems until approved.</p>{error?<p className={styles.error}>{error}</p>:null}<button className={styles.primary} disabled={busy}>{busy?"Uploading…":"Upload for Review"}</button></form></section></div>;
}

function Overview({ b }: { b: BrandDetail }) {
  const checklist = [["Logo",b.logoCount>0],["Colors",b.colors.length>1],["Typography",Boolean(b.primaryFont)],["Messaging",Boolean(b.tagline&&b.tone&&b.audience&&b.primaryCta)],["Templates",b.templateCount>0],["Guidelines",b.guidelines.length>0]] as const;
  return <><div className={detail.four}><Section title="Brand Identity"><div className={detail.identityCard}><div className={detail.bigLogo}>{b.logoUrl ? <Image src={b.logoUrl} alt="" fill sizes="100px"/> : b.name.slice(0,2).toUpperCase()}</div><p>{b.tagline || "No tagline configured"}</p><div className={detail.palette}>{b.colors.map((c,i)=><i key={`${c}-${i}`} style={{background:c}} title={c}/>)}</div><small>{b.primaryFont || "Primary font not set"}</small></div></Section><Section title="Brand Voice"><dl><dt>Tone</dt><dd>{b.tone||"Not set"}</dd><dt>Target Audience</dt><dd>{b.audience||"Not set"}</dd><dt>Core Message</dt><dd>{b.coreMessage||"Not set"}</dd><dt>Primary CTA</dt><dd>{b.primaryCta||"Not set"}</dd></dl></Section><Section title="Assets"><div className={detail.metricGrid}><span><b>{b.assetCount}</b>Total Assets</span><span><b>{b.templateCount}</b>Templates</span><span><b>{b.logoCount}</b>Logos</span><span><b>{b.assets.filter(a=>a.assetType==="brand_graphic").length}</b>Graphics</span></div></Section><Section title="Brand Health"><div className={detail.score}><b>{b.completeness}%</b><span>{label(b.health)}</span></div><ul className={detail.checks}>{checklist.map(([n,ok])=><li key={n}><i className={ok?detail.ok:detail.missing}>{ok?<IconCheck size={11}/>:"!"}</i>{n}<span>{ok?"Complete":"Missing"}</span></li>)}</ul></Section></div><div className={detail.split}><Section title="Recently Added Assets">{b.assets.length?<div className={detail.assetStrip}>{b.assets.slice(0,4).map(a=><div key={a.id}>{a.url?<Image src={a.url} alt="" fill sizes="140px"/>:<IconFile/>}<span>{a.title}</span></div>)}</div>:<Empty title="No assets yet" text="Upload the first approved brand asset."/>}</Section><Section title="Recent Activity">{b.activity.length?<ul className={detail.activity}>{b.activity.slice(0,6).map((a)=><li key={String(a.id)}><b>{label(String(a.action))}</b><span>{String(a.detail||"")}</span><time>{new Date(String(a.created_at)).toLocaleDateString()}</time></li>)}</ul>:<Empty title="No activity yet" text="Brand changes will be recorded here."/>}</Section></div></>;
}

function AssetGallery({ b, logos=false }: { b: BrandDetail; logos?: boolean }) { const rows=b.assets.filter(a=>!logos||a.assetType==="logo"); return rows.length?<div className={detail.gallery}>{rows.map(a=><article key={a.id}><div>{a.url&&a.mimeType?.startsWith("image/")?<Image src={a.url} alt="" fill sizes="250px"/>:<IconFile size={30}/>}</div><h3>{a.title}</h3><p>{label(a.role||a.assetType)} · {a.width&&a.height?`${a.width}×${a.height}`:"Dimensions unavailable"}</p><span className={detail.status}>{label(a.approvalStatus)}</span></article>)}</div>:<Empty title={logos?"No logos yet":"No assets yet"} text={logos?"Upload a logo or create one in Logo Studio.":"Upload an approved brand asset."}/>; }

function Messaging({ b }: { b: BrandDetail }) { return <form action={saveMessagingAction} className={detail.editor}><input type="hidden" name="brand_id" value={b.id}/><div className={detail.two}><label>Brand Tagline<input name="tagline" defaultValue={b.tagline||""}/></label><label>Tone of Voice<input name="tone" defaultValue={b.tone||""} placeholder="Professional, technical, friendly…"/></label></div><label>Short Company Description<textarea name="short_description" defaultValue={b.description||""} rows={2}/></label><label>Long Company Description<textarea name="long_description" defaultValue={b.longDescription||""} rows={4}/></label><div className={detail.two}><label>Mission<textarea name="mission" defaultValue={b.mission||""} rows={3}/></label><label>Vision<textarea name="vision" defaultValue={b.vision||""} rows={3}/></label></div><label>Core Message<textarea name="core_message" defaultValue={b.coreMessage||""} rows={3}/></label><div className={detail.two}><label>Target Audience<textarea name="audience" defaultValue={b.audience||""} rows={3}/></label><label>Ideal Customer<textarea name="ideal_customer" defaultValue={b.idealCustomer||""} rows={3}/></label></div><div className={detail.two}><label>Core Services<textarea name="core_services" defaultValue={listText(b.coreServices)} rows={2}/></label><label>Key Differentiators<textarea name="differentiators" defaultValue={listText(b.differentiators)} rows={2}/></label></div><div className={detail.two}><label>Primary CTA<input name="primary_cta" defaultValue={b.primaryCta||""}/></label><label>Secondary CTA<input name="secondary_cta" defaultValue={b.secondaryCta||""}/></label></div><label>Free-text Tone Guidance<textarea name="tone_guidance" defaultValue={b.toneGuidance||""} rows={4}/></label><div className={detail.two}><label>Words / Phrases to Use<textarea name="preferred_phrases" defaultValue={listText(b.preferredPhrases)} rows={3}/></label><label>Restricted Terminology<textarea name="prohibited_phrases" defaultValue={listText(b.prohibitedPhrases)} rows={3}/></label></div><label>Claims Requiring Approval<textarea name="claims_requiring_approval" rows={2}/></label><button className={styles.primary}>Save Approved Brand Context</button></form>; }

function Colors({ b }: { b: BrandDetail }) { return <><div className={detail.colorGrid}>{b.colorsDetailed.map(c=><article key={c.id}><i style={{background:c.hex}}/><div><h3>{c.name}</h3><code>{c.hex}</code><p>{label(c.role)}{c.usageNotes?` · ${c.usageNotes}`:""}</p></div></article>)}</div><Section title="Add Color"><form action={addColorAction} className={detail.inlineForm}><input type="hidden" name="brand_id" value={b.id}/><label>Name<input name="name" required/></label><label>Color<input name="hex" type="color" defaultValue="#168fff"/></label><label>Role<select name="role"><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="accent">Accent</option><option value="background">Background</option><option value="surface">Surface</option><option value="text">Text</option><option value="custom">Custom</option></select></label><label>Usage Notes<input name="usage_notes"/></label><button className={styles.primary}><IconPlus size={14}/> Add Color</button></form></Section></>; }

function Typography({ b }: { b: BrandDetail }) { return <><div className={detail.typeGrid}>{b.typography.map(t=><article key={t.id}><small>{label(t.role)}</small><h3 style={{fontFamily:t.fontName}}>{t.fontName} {t.weight}</h3><p style={{fontFamily:t.fontName}}>The Future of Business Starts Here</p><span>ABCDEFGHIJKLMNOPQRSTUVWXYZ</span><em>{t.usageNotes||t.fallback||"No usage notes"}</em></article>)}</div><Section title="Add Typography"><form action={addTypographyAction} className={detail.inlineForm}><input type="hidden" name="brand_id" value={b.id}/><label>Font Name<input name="font_name" required/></label><label>Weight<input name="weight" placeholder="400 / Regular"/></label><label>Role<select name="role"><option value="h1">H1</option><option value="h2">H2</option><option value="h3">H3</option><option value="body">Body</option><option value="caption">Caption</option><option value="button">Button</option><option value="quote">Quote</option></select></label><label>Fallback Stack<input name="fallback_stack"/></label><button className={styles.primary}><IconPlus size={14}/> Add Font</button></form></Section></>; }

function Guidelines({ b }: { b: BrandDetail }) { const sections=["Logo Usage","Color Usage","Typography","Photography","Social Media","Email","Advertising","Website","Tone of Voice","Do / Don’t","Legal / Required Disclaimers"]; return <div className={detail.guides}>{sections.map(s=>{const g=b.guidelines.find(v=>v.section===s);return <form action={saveGuidelineAction} key={s}><input type="hidden" name="brand_id" value={b.id}/><input type="hidden" name="section" value={s}/><h3>{s}</h3><textarea name="content" defaultValue={String(g?.content||"")} rows={4} placeholder={`Add ${s.toLowerCase()} guidance…`}/><button className={styles.secondary}>Save Section</button></form>})}</div>; }

function Templates({ b }: { b: BrandDetail }) { return <><div className={detail.gallery}>{b.templates.map(t=><article key={String(t.id)}><div><IconFile size={30}/></div><h3>{String(t.name)}</h3><p>{label(String(t.template_type))} · {t.width&&t.height?`${t.width}×${t.height}`:"Custom size"}</p><span className={detail.status}>{label(String(t.status))}</span></article>)}</div>{!b.templates.length?<Empty title="No templates yet" text="Create a reusable branded template."/>:null}<Section title="Create Template"><form action={saveTemplateAction} className={detail.inlineForm}><input type="hidden" name="brand_id" value={b.id}/><label>Name<input name="name" required/></label><label>Type<select name="template_type"><option value="instagram_post">Instagram Post</option><option value="instagram_story">Instagram Story</option><option value="facebook_ad">Facebook Ad</option><option value="linkedin_post">LinkedIn Post</option><option value="email_header">Email Header</option><option value="proposal_cover">Proposal Cover</option><option value="website_hero">Website Hero</option><option value="custom">Custom</option></select></label><label>Width<input name="width" type="number" min="1"/></label><label>Height<input name="height" type="number" min="1"/></label><button className={styles.primary}><IconPlus size={14}/> Create</button></form></Section></>; }

function Settings({ b }: { b: BrandDetail }) { return <><form action={saveBrandKitAction} className={detail.editor}><input type="hidden" name="brand_id" value={b.id}/><div className={detail.two}><label>Brand Name<input name="name" defaultValue={b.name} required/></label><label>Internal Name<input name="internal_name" defaultValue={b.internalName||""}/></label></div><div className={detail.two}><label>Brand Type<select name="brand_type" defaultValue={b.brandType}><option value="internal">Internal</option><option value="client">Client Brand</option><option value="white_label">White Label</option><option value="product">Product Brand</option><option value="sub_brand">Sub-Brand</option></select></label><label>Status<select name="status" defaultValue={b.status}><option value="active">Active</option><option value="draft">Draft</option><option value="needs_review">Needs Review</option><option value="incomplete">Incomplete</option><option value="paused">Paused</option></select></label></div><div className={detail.two}><label>Industry<input name="industry" defaultValue={b.industry||""}/></label><label>Primary Font<input name="primary_font" defaultValue={b.primaryFont||""}/></label></div><label>Description<textarea name="description" defaultValue={b.description||""} rows={3}/></label><label>Tagline<input name="tagline" defaultValue={b.tagline||""}/></label><button className={styles.primary}>Save Brand Settings</button></form><form action={archiveBrandAction} className={detail.danger}><input type="hidden" name="brand_id" value={b.id}/><div><b>Archive brand kit</b><p>Removes it from active selectors without deleting its assets or history.</p></div><button>Archive</button></form></>; }

export default function BrandKitDetail({ brand:b, tab, canManage }: { brand:BrandDetail; tab:string; canManage:boolean }) {
  const [upload,setUpload]=useState(false); const active=TABS.includes(tab)?tab:"overview";
  let content:React.ReactNode;
  if(active==="overview")content=<Overview b={b}/>; else if(active==="logos")content=<AssetGallery b={b} logos/>; else if(active==="colors")content=<Colors b={b}/>; else if(active==="typography")content=<Typography b={b}/>; else if(active==="media")content=<AssetGallery b={b}/>; else if(active==="templates")content=<Templates b={b}/>; else if(active==="messaging")content=<Messaging b={b}/>; else if(active==="guidelines")content=<Guidelines b={b}/>; else if(active==="usage")content=b.assets.some(a=>a.usageCount)?<ul className={detail.usage}>{b.assets.filter(a=>a.usageCount).map(a=><li key={a.id}><b>{a.title}</b><span>{a.usageCount} recorded uses</span></li>)}</ul>:<Empty title="No recorded usage" text="Only application references are counted; the system does not fabricate analytics."/>; else if(active==="activity")content=b.activity.length?<ul className={detail.activity}>{b.activity.map(a=><li key={String(a.id)}><b>{label(String(a.action))}</b><span>{String(a.detail||"")}</span><time>{new Date(String(a.created_at)).toLocaleString()}</time></li>)}</ul>:<Empty title="No activity yet" text="Edits and reviews will appear here."/>; else if(active==="settings")content=canManage?<Settings b={b}/>:<Empty title="View only" text="Only administrators can change core identity."/>; else content=<Empty title={`No ${active} yet`} text="Create the first record for this brand kit."/>;
  return <div className={detail.page}><Link className={detail.back} href={ROOT}>← All Brand Assets</Link><header className={detail.head}><div className={detail.headLogo}>{b.logoUrl?<Image src={b.logoUrl} alt="" fill sizes="70px"/>:b.name.slice(0,2).toUpperCase()}</div><div><h1>{b.name}</h1><p>{b.tagline||"Brand system"}</p><div><span>{label(b.status)}</span><span>{label(b.brandType)}</span><span>{b.clientName||"Internal"}</span></div></div><aside><button className={styles.primary} onClick={()=>setUpload(true)}><IconPlus size={14}/> Upload Asset</button><Link className={styles.secondary} href="/logo-studio" target="_blank">Open Logo Studio</Link>{canManage?<Link className={styles.secondary} href={`?tab=settings`}>Edit Brand</Link>:null}</aside></header><section className={detail.summary}><div><small>Primary Logo</small><b>{b.logoCount?"Configured":"Missing"}</b></div><div><small>Primary Color</small><b>{b.colors[0]||"Missing"}</b></div><div><small>Background Color</small><b>{b.colors[2]||"Not set"}</b></div><div><small>Primary Font</small><b>{b.primaryFont||"Missing"}</b></div><div><small>Brand Health</small><b>{b.completeness}% · {label(b.health)}</b></div></section><nav className={detail.tabs}>{TABS.map(t=><Link className={active===t?detail.active:""} href={`?tab=${t}`} key={t}>{label(t)}</Link>)}</nav><main>{content}</main>{upload?<UploadModal b={b} close={()=>setUpload(false)}/>:null}</div>;
}
