export const SERVICE_STATUSES = ['active', 'draft', 'paused', 'retired'] as const;
export const SERVICE_TYPES = ['Website', 'Hosting', 'AI Solution', 'Software', 'Marketing', 'SEO', 'Social Media', 'Logo / Branding', 'Consulting', 'Custom'] as const;
export const BILLING_TYPES = ['one_time', 'recurring', 'usage_based', 'custom_quote'] as const;
export const BILLING_LABELS: Record<string, string> = { one_time: 'One-Time', recurring: 'Recurring', usage_based: 'Usage-Based', custom_quote: 'Custom Quote' };
export const SERVICE_FREQUENCIES = ['one_time', 'daily', 'weekly', 'monthly', 'quarterly', 'annually', 'as_needed', 'custom'] as const;
export const FREQUENCY_LABELS: Record<string, string> = { one_time: 'One-Time', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', quarterly: 'Quarterly', annually: 'Annually', as_needed: 'As Needed', custom: 'Custom' };
export const SERVICE_HEALTH_LABELS: Record<string, string> = { healthy: 'Healthy', needs_attention: 'Needs Attention', low_margin: 'Low Margin', no_clients: 'No Clients', missing_cost: 'Missing Cost' };
export const AVAILABILITY = { catalog_enabled: 'Available in Catalog', proposal_enabled: 'Available in Proposals', intake_enabled: 'Available in Client Intake', internal_sales_enabled: 'Available for Internal Sales', public_enabled: 'Available for Public Website', manual_invoice_enabled: 'Allow Manual Invoice Addition', featured: 'Featured Service', requires_quote: 'Requires Custom Quote', requires_approval: 'Requires Approval Before Sale', discount_eligible: 'Discount Eligibility' } as const;
export type ServiceStatus = typeof SERVICE_STATUSES[number];
export type Service = {
  id: string; name: string; sku: string | null; description: string | null; category: string; service_type: string;
  slug: string | null; catalog_category: string | null; short_description: string | null; image_url: string | null; image_path: string | null; image_alt: string | null; icon_key: string | null; public_route: string | null; meta_title: string | null; meta_description: string | null; frontend_locations: string[]; package_count?: number;
  status: ServiceStatus; billing_type: typeof BILLING_TYPES[number]; billing_interval: string; interval_months: number;
  from_cents: number; setup_fee_cents: number; internal_cost_cents: number | null; recurring_cost_cents: number | null;
  effective_cost_cents: number | null; calculated_internal_cost_cents: number | null; component_cost_cents: number | null;
  gross_profit_cents: number | null; health: 'healthy' | 'needs_attention' | 'low_margin' | 'no_clients' | 'missing_cost';
  software_cost_cents: number | null; ai_api_cost_cents: number | null; hosting_cost_cents: number | null; contractor_cost_cents: number | null;
  labor_hours: number | null; labor_hourly_rate_cents: number | null; ad_platform_cost_cents: number | null; other_cost_cents: number | null; cost_notes: string | null;
  discount_rules: string | null; custom_pricing_allowed: boolean; minimum_contract_months: number; trial_days: number; renewal_settings: string | null; margin_threshold_pct: number;
  taxable: boolean; position: number; created_at: string; updated_at: string;
  active_clients: number; subscriptions: number; mrr_cents: number; revenue_cents: number; sales_count: number; margin: number | null;
} & Record<keyof typeof AVAILABILITY, boolean>;
export type ServiceOption = Pick<Service, 'id' | 'name' | 'description' | 'from_cents' | 'billing_type' | 'billing_interval' | 'interval_months' | 'setup_fee_cents' | 'taxable' | 'requires_quote' | 'requires_approval'>;
export type Assignment = { id: string; service_id: string; customer_id: string; client_name: string; status: string; sale_price_cents: number; billing_type: string; interval_months: number; start_date: string; end_date: string | null; next_billing_date: string | null; subscription_id: string | null; job_id: string | null; revenue_cents: number; assigned_manager: string | null; billing_status: string };
export type Sale = { service_id: string; invoice_id: string; invoice_number: string; customer_id: string | null; client_name: string | null; proposal_id: string | null; amount_cents: number; occurred_at: string; owner: string | null; billing_type: string; status: string };
export type PackageRelationship = { id: string; service_id: string; package_id: string; relationship_type: 'included' | 'addon'; quantity: number; notes: string | null; package_name: string };
export type Automation = { service_id: string; create_project: boolean; task_template_id: string | null; default_assignee: string | null; due_date_offset_days: number; notify_admin: boolean };
export type ServiceInclusion = { id: string; service_id: string; name: string; description: string | null; quantity: number | null; frequency: string; custom_frequency: string | null; is_included: boolean; is_optional_addon: boolean; client_facing_description: string | null; internal_notes: string | null; sort_order: number };
export type ServiceDeliverable = { id: string; service_id: string; name: string; description: string | null; quantity: number | null; frequency: string; custom_frequency: string | null; client_facing_description: string | null; internal_notes: string | null; sort_order: number; automation_key: string | null };
export type TopService = { id: string; name: string; mrr_cents: number; revenue_cents: number };
export type ServiceSummary = { active_services: number; mrr_cents: number; revenue_cents: number; recurring_revenue_cents: number; one_time_cents: number; subscriptions: number; active_clients: number; average_margin: number | null; top_services: TopService[] };
export type ActionResult = { error?: string; success?: string; id?: string };
